### ISSUE TITLE
Tooling Issue with Binding direction

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1507] opened 2017-05-12 23:14 UTC
The logic our VS tooling uses to determine the direction of a binding is too simple. E.g. currently it (from @ahmelsayed):

- assume it's "out"
- if it's a trigger, then it's "in"
- if there is a FileAccess property on the attribute, then use it

However, for many input bindings (e.g. Bot IDirectLineClient, NotificationHubClient, etc.) this doesn't work, and ends up generating incorrect metadata, causing runtime failures.

We need to update IJobHostMetadataProvider to be able to serve the correct information.

**Comment by mathewc** [comment] 2017-05-12 23:16
See original issue: https://github.com/Microsoft/BotBuilder-WebJobs-BotExtension/issues/5

**Comment by MikeStall** [comment] 2017-05-12 23:24
The ideal fix is https://github.com/Azure/azure-webjobs-sdk-script/issues/1508 

That's complicated. 
- We could make short term tactical fixes. The VS tooling could match to 'out' via the parameter signature (out T, ICollector<T>, etc)  
- more accurate would be to traverse the graph.

**Comment by colbylwilliams** [comment] 2017-05-13 00:09
Correct me if I'm wrong, but the project type included with the new VS tooling requires the use of attribute-based binding -  there's no way to "opt out" and manually provide the function.json file?   If that's the case, what is the best alternative approach to writing Azure Functions with VS17?  Create an empty asp web app and call the command line tools post build?

**Comment by mathewc** [comment] 2017-05-13 00:32
@paulbatum and I just tried and we were unable to get the workaround of providing your own function.json to work, though we think it should. @lindydonna might know of a way?

**Comment by lindydonna** [comment] 2017-05-13 03:33
Make sure you set function.json to copy to output directory, and use the same folder name as function. You can't use attributes in that same function though, because the output will be overwritten by the build step. Perhaps that's what you meant?

**Comment by colbylwilliams** [comment] 2017-05-13 17:04
Not what I meant, but makes perfect sense.  I'll give that a shot. Thanks.

**Comment by colbylwilliams** [comment] 2017-05-15 04:35
@lindydonna Unfortunately I couldn't get your suggestion to work.  As soon as a add a `MyFunctionName\function.json` to the csproj, the `MyFunctionName` directory isn't added to the output directory on build.  
Now, if I try the same thing with a new json file named anything other than function.json, it copies the file to the output directory as expected.  Not sure what I'm doing wrong, or if its a bug in the build step.  My project is [here][0], and the specific function is [`GetBotToken`][1]

[0]:https://github.com/colbylwilliams/Agencies/tree/master/Agencies/Agencies.Functions
[1]:https://github.com/colbylwilliams/Agencies/blob/master/Agencies/Agencies.Functions/BotTokenGenerator.cs#L27

**Comment by lindydonna** [comment] 2017-05-15 17:07
@ahmelsayed Could you take a look?

**Comment by ahmelsayed** [comment] 2017-05-15 17:11
the problem is you fighting with the cleanup logic for the build task which deletes any folder with a function.json in it. Let me think about it.

**Comment by lindydonna** [comment] 2017-05-15 17:19
@colbylwilliams I've created this issue to track the function.json problem: https://github.com/Azure/azure-functions-vs-build-sdk/issues/44

**Comment by paulbatum** [comment] 2017-05-19 22:48
@mathewc will work with @ahmelsayed on getting the right fix into the MakeFunctionJson tool until the real fix #1508 happens.

**Comment by paulbatum** [comment] 2017-05-19 22:51
I also moved the discussion about being able to manually add a function.json when using the VS tooling to https://github.com/Azure/azure-functions-vs-build-sdk/issues/50

**Comment by lindydonna** [comment] 2017-07-07 22:41
Closing in favor of #1508.

**Closed by lindydonna** 2017-07-07 22:41 UTC
Labels: swimlane:dotnet-dev-experience
