### ISSUE TITLE
NuGet Cycle detected with ImageResizer NuGet package

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1127] opened 2017-01-18 00:37 UTC
_From @bcnzer on November 23, 2016 9:3_

(This is my first-ever GitHub issue so please bear with me!)

I'm trying to build a simple Azure function that triggers on blobs, in order to resize images. Instructions are: http://jameschambers.com/2016/11/Resizing-Images-Using-Azure-Functions/

I added a project.json and a reference to ImageResizer as per below
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "ImageResizer": "4.0.5"
      }
    }
   }
}
```
Once I do and hit save the logs say "Cycle detected". Later on I get errors when it says it can't find the namespace ImageResizer. 
```
2016-11-23T08:50:54.284 D:\home\site\wwwroot\MyImageResizer\project.json
2016-11-23T08:50:54.284 Restore failed in 445ms.
2016-11-23T08:50:54.299 
2016-11-23T08:50:54.299 Errors in D:\home\site\wwwroot\MyImageResizer\project.json
2016-11-23T08:50:54.299 Cycle detected:
2016-11-23T08:50:54.299 MyImageResizer (>= 1.0.0) -> ImageResizer (>= 4.0.5) -> ImageResizer (>= 4.0.4) -> ImageResizer (>= 4.0.4).
2016-11-23T08:50:54.299 
2016-11-23T08:50:54.299 NuGet Config files used:
2016-11-23T08:50:54.299 C:\DWASFiles\Sites\spotterplfunc\AppData\NuGet\NuGet.Config
2016-11-23T08:50:54.299 
2016-11-23T08:50:54.299 Feeds used:
2016-11-23T08:50:54.299 https://api.nuget.org/v3/index.json
2016-11-23T08:50:54.336 
2016-11-23T08:50:54.336 
2016-11-23T08:50:54.362 Packages restored.
2016-11-23T08:50:54.674 Script for function 'MyImageResizer' changed. Reloading.
2016-11-23T08:50:54.768 (3,7): error CS0246: The type or namespace name 'ImageResizer' could not be found (are you missing a using directive or an assembly reference?)
2016-11-23T08:50:54.768 (11,24): error CS0246: The type or namespace name 'ImageResizer' could not be found (are you missing a using directive or an assembly reference?)
2016-11-23T08:50:54.768 (16,5): error CS0103: The name 'ImageResizer' does not exist in the current context
2016-11-23T08:50:54.768 Compilation failed.
```

Please note that I have tried changing the version from 4.0.4 > 4.0.5 as suggested in issue #796. Also tried recreating it, etc. It's pretty consistent.  
```
#r "System.Drawing"

using ImageResizer;
using System.Drawing;
using System.Drawing.Imaging;

public static void Run(Stream myBlob, string name, Stream outputBlob, TraceWriter log)
{
    log.Info($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");

    var settings = new ImageResizer.ResizeSettings{
        MaxWidth = 500,
        Format = "png"
    }; 

    ImageResizer.ImageBuilder.Current.Build(myBlob, outputBlob, settings);

}
```

_Copied from original issue: projectkudu/AzureFunctionsPortal#814_

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @davidfowl on November 23, 2016 9:38_

Change the name of your project... Is it ImageResizer?

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @christopheranderson on November 23, 2016 18:28_

@fabiocav is looking into this now - we may need to move this into https://github.com/Azure/azure-webjobs-sdk-script

**Comment by lindydonna** [comment] 2017-01-18 00:37
@davidfowl Thanks for the comment. Just out of curiosity, how did you find this random issue? :)

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @davidfowl on November 23, 2016 18:44_

@lindydonna I see all... 😄

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @fabiocav on November 23, 2016 19:1_

Interesting to see this happening with the function name you have above. This will typically occur if the function name (therefore the folder name) matches the name of the package you're referencing as it will be treated as the project name.

It's a bit odd that I couldn't find much information using that function name you've shared. Would you be able to share your Function App (site) name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? 

This **bolded bit** is particularly interesting: ( @davidfowl, any thoughts on this?)
MyImageResizer (>= 1.0.0) -> **ImageResizer (>= 4.0.5) -> ImageResizer (>= 4.0.4)** -> ImageResizer (>= 4.0.4

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @davidfowl on November 24, 2016 7:17_

That's super strange. @fabiocav what does the folder look like behind the scenes? What does the `project.json` and `project.lock.json` look like for this project?

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @bcnzer on November 24, 2016 7:41_

@fabiocav Sorry, the version I have now - that is live - its called CompImageResizer. I re-created this Azure Function over several times, thinking I did something wrong (this is my first Azure Function)

I don't think it has anything to do with the name ImageResizer. I created another function called **AFIssue814**, using the BlobTrigger-CSharp template and all I did was add a project.json with that one dependency and then I see....

```
2016-11-24T07:37:14.979 
2016-11-24T07:37:14.979 Errors in D:\home\site\wwwroot\AFIssue814\project.json
2016-11-24T07:37:14.979 Cycle detected:
2016-11-24T07:37:14.979 AFIssue814 (>= 1.0.0) -> ImageResizer (>= 4.0.5) -> ImageResizer (>= 4.0.4) -> ImageResizer (>= 4.0.4).

```

@davidfowl For my CompImageResizer (which is currently live) as well as my AFIssue814 Azure function which I just-created, both have the identical project.json with...

```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "ImageResizer": "4.0.5"
      }
    }
   }
}
```

and an identical project.json.lock with...
```
{
  "version": 2,
  "targets": {
    ".NETFramework,Version=v4.6": {
      "ImageResizer/1.0.0": {
        "type": "project",
        "framework": ".NETFramework,Version=v4.6",
        "dependencies": {
          "ImageResizer": "4.0.4"
        }
      }
    }
  },
  "libraries": {
    "ImageResizer/1.0.0": {
      "type": "project",
      "path": "../ImageResizer/project.json"
    }
  },
  "projectFileDependencyGroups": {
    "": [],
    ".NETFramework,Version=v4.6": [
      "ImageResizer >= 4.0.5"
    ]
  },
  "tools": {},
  "projectFileToolGroups": {},
  "packageFolders": {
    "D:\\home\\data\\Functions\\packages\\nuget": {}
  }
}
```

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @fabiocav on November 24, 2016 8:5_

@spottersys do you still have a function called `ImageResizer` in `d:\home\site\wwwroot`? Looks like that is being picked up. Can you delete that function and retry?

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @bcnzer on November 24, 2016 8:20_

@fabiocav yes I do. I wasn't using that version (forgot it was there really) and now that I've deleted it, everything is working - in my other AFs. Thank you!

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @fabiocav on November 24, 2016 9:29_

That is expected restore behavior, but as we just experience, may be confusing in the context of functions.

We might have some options to prevent this from happening, will investigate a couple of options. (@davidfowl any thoughts on this?)

At the very least, we can detect the issue and provide a clearer error message in those cases.

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @davidfowl on November 24, 2016 15:41_

The lock file reveals all! It was seeing image resizer as a project reference. You might just need to restructure how functions are laid out on disk so that they aren't sibling folders. If that's not feasible, we might be able to come up with something else

**Comment by lindydonna** [comment] 2017-01-18 00:37
_From @fabiocav on November 24, 2016 16:13_

It indeed gave us what we needed to figure out what was happening! :)

Changing the directory structure would be a pretty significant change to the runtime and would impact tooling, documentation, portal, etc. So that's not a viable option (at least not in this version)

I've played with a couple of options last night:

1. Project files named after the function (e.g.using the `{projectname}.project.json` format) this would require some changes to the runtime, but not too impactful. Still a bit fragile as we still, for the most part, rely on users to create the file. We would need better tooling/portal support to follow this convention (not a bad thing, just something we don't have yet)
2. The runtime could perform the restore in a different temp folder location with a structure it controls, we would then move the lock file to the function folder at the end. This is probably the least impactful and most promising option.
3. Perhaps a way we could use `global.json` playing with projects to influence that behavior (just an idea, I don't really think this would work)

Option 2 is the best option at the moment, but I'd love to hear any other suggestions you may have.

**Comment by lindydonna** [comment] 2017-01-18 00:37
Did we want this issue to be closed?  I'll reopen and @fabiocav can close if necessary. Also, we need to move to the -script repo if it is still a open issue.

**Comment by fabiocav** [comment] 2017-01-18 05:45
We can create a separate issue to address the root cause if desired (it would be an enhancement to prevent similar issues), but I believe this is pretty low priority at the moment (principally after the template changes). I did a quick log scan a while back and didn't see any other instances of this happening.

**Comment by christopheranderson** [comment] 2017-01-20 18:52
Close this since template change addressed main source of the issue. We can open another issue if it comes again.

**Closed by christopheranderson** 2017-01-20 18:52 UTC
