### ISSUE TITLE
Timer Trigger Cron Expression Invalid

### ISSUE THREAD

**Issue by hershize** [Azure/azure-webjobs-sdk-script#2210] opened 2017-12-08 17:08 UTC
I am using a timer trigger to schedule a job every week day at 8 AM. I am using this expression `0 0 8 * * 1-5`. The script host is giving an error saying that the cron expression is invalid.

![image](https://user-images.githubusercontent.com/12899565/33776808-2ed50768-dc08-11e7-981e-c437dc3a1abb.png)
![image](https://user-images.githubusercontent.com/12899565/33776829-40b53c78-dc08-11e7-8ca2-a8fa99310f77.png)
![image](https://user-images.githubusercontent.com/12899565/33776982-bba06ea8-dc08-11e7-93bc-0091b20ae454.png)

Any insights into this?

**Comment by tohling** [comment] 2017-12-08 19:00
To set it to run every weekday at 8 AM, you will need the cron expression `0 0 8 * * 1-5` (as correctly set in your question).

The issue is with the expression used in your code. Your code is using `0 8 * * 1-5`, which is invalid.  Fix the cron expression in your code and the error should go away.

**Comment by hershize** [comment] 2017-12-08 19:34
I tried `0 0 8 * * 1-5` as well in the function. Still didn't work.

**Comment by tohling** [comment] 2017-12-08 19:55
I cannot repro the error.  Here are the screenshots of my code and output:

**Code:**

![timer](https://user-images.githubusercontent.com/14911331/33782671-7c1c5142-dc0e-11e7-9762-8e509339b196.PNG)

**Azure.Functions.Cli output:**

![timer2](https://user-images.githubusercontent.com/14911331/33782675-81d9620a-dc0e-11e7-9be8-f93dabce7e41.PNG)

**Comment by hershize** [comment] 2017-12-08 20:52
I was using v1.0.7 of the functions CLI. I suppose that could be the problem. I upgraded to v2.0.1-beta.22 and it worked soon after that. Anyways, thanks for assisting!

**Comment by tohling** [comment] 2017-12-09 04:21
Great! Glad that you are unblocked. I will close this issue now.

**Closed by tohling** 2017-12-09 04:21 UTC
