### ISSUE TITLE
Azure Functions: Function crashes AppService (We are unable to reach your function app (Not Found). Please try again later)

### ISSUE THREAD

**Issue by lucabol** [Azure/azure-webjobs-sdk-script#982] opened 2016-11-24 13:14 UTC
It seems that every time dotnet restore fails, the whole appservice crashes.

#### Repro steps

1. Open the editor for https://ms.portal.azure.com/#blade/WebsitesExtension/FunctionsIFrameBlade/id/%2Fsubscriptions%2F818e194a-9bee-486f-9854-03b3be61170b%2Fresourcegroups%2FFollowTheGuru%2Fproviders%2FMicrosoft.Web%2Fsites%2FFollowTheGuru
2. Wait a few seconds

#### Expected behavior

A normal error, not a catastrophic crash

#### Actual behavior

We are unable to reach your function app (Not Found). Please try again later)

**Comment by lindydonna** [comment] 2016-11-29 22:04
This is actually a problem with the error message which should really be improved. @lucabol Could you look at issue https://github.com/projectkudu/AzureFunctionsPortal/issues/817 and see if that would have caused less confusion?

The problem is that a 404 is the right error code, because that function can't be found and can't be called. The portal message makes it sound as though the whole app was broken, which is not the case.

**Comment by lucabol** [comment] 2016-11-29 22:24
Certainly so. But I think it is a symptom of a deeper problem, that the compilation/runtime mode is not transparent. We can chat a bit more about it in person. Perhaps I am wrong.

**Comment by lindydonna** [comment] 2016-11-29 22:33
Yes, you're absolutely right about this, this is a known issue that we want to improve. Compilation errors should not appear in the same place as runtime.

**Comment by lindydonna** [comment] 2016-12-05 16:54
@lucabol I've created https://github.com/projectkudu/AzureFunctionsPortal/issues/829 to track the issue of compilation vs. runtime logs.

Closing this issue as the fixes are now tracked by https://github.com/projectkudu/AzureFunctionsPortal/issues/817 and https://github.com/projectkudu/AzureFunctionsPortal/issues/829

**Closed by lindydonna** 2016-12-05 16:54 UTC

**Comment by ship2moon** [comment] 2016-12-07 23:24
I am getting this error on my blob trigger function app "We are unable to reach your function app (Service Unavailable). Please try again later." and then I am getting a 403 while trying to open the function app in the browser. But I am able to view / edit the function C# code or the "integrate" configuration successfully.

**Comment by lindydonna** [comment] 2016-12-16 02:35
@ship2moon We don't track closed issues and your comment looks looks like it's unrelated to the original issue that was opened. Please start a thread on the forums for technical help: https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions
