### ISSUE TITLE
Request body in Test slice becomes read-only when you change the HTTP method

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-webjobs-sdk-script#1618] opened 2017-06-22 15:44 UTC
If change the HTTP method (selecting GET in the combo box) in the Test slice/panel, the Request body area of that panel becomes read-only until you refresh your window.

#### Repro steps

1. Create a new C# HTTP function in your function app.
2. Click on Test on the right side of the UI to open the Test slice/panel.
3. Modify the request body -- this works as expected.
4. Click on the combo box under HTTP method and select "GET".
5. Try to modify the request body -- this does not work.
6. Click Run to run the function (this saves the GET selection you just made).
7. Refresh your window or browse away from the function and then back to it.
8. Now you can modify the request body.

#### Expected behavior

You should be able to modify the request body even after selecting GET.

#### Actual behavior

You cannot modify the request body unless you use the workaround.

#### Known workarounds

See steps 7 and 8, above.

#### Related information 

* C#
* Use the default HTTP function to test this

**Comment by ahmelsayed** [comment] 2017-06-22 15:49
This is by design. GET requests don't have a body. https://tools.ietf.org/html/rfc2616#section-9.3

**Comment by mathewc** [comment] 2017-06-22 15:52
@ahmelsayed is correct - closing this.

**Closed by mathewc** 2017-06-22 15:52 UTC

**Comment by KirkMunro** [comment] 2017-06-22 16:38
Shouldn't the body be removed if you set the verb to GET though? Or disabled? Right now you can still modify it via the workaround. The modification I was making was actually just to remove what was there. So if body doesn't apply, and you're closing this, then you have a different bug because you can modify the body when the verb is GET as described above.

**Comment by ahmelsayed** [comment] 2017-06-23 03:07
@KirkMunro can you please open that other issue over at https://github.com/Azure/azure-functions-ux?
