### ISSUE TITLE
Control number of Events processed parallely by azure function

### ISSUE THREAD

**Issue by aloysiustany** [Azure/azure-webjobs-sdk-script#2241] opened 2017-12-20 04:15 UTC
I am trying to limit the number of events that are picked up and processed by my eventhub triggered azure function.

I have the value of eventHub:maxBatchSize in host.json to 8. But I can see that more than 8 events are being processed at a time. What should be the value of eventHub:prefetchCount ? Would it make a difference to change prefetchCount to achieve my goal (it is currently default) ?

Note: My azure function runs in an appservice plan.

**Comment by kashimiz** [comment] 2017-12-28 22:26
Duplicate of #1649

**Comment by christopheranderson** [comment] 2018-01-16 18:48
Closing as duplicate.

**Closed by christopheranderson** 2018-01-16 18:48 UTC
