### ISSUE TITLE
[Visual Studio] Functions project name cannot have a period

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-webjobs-sdk-script#1021] opened 2016-12-02 20:34 UTC
Azure Functions projects will fail to run if the project was created using a name that contains a period.

#### Repro steps

Provide the steps required to reproduce the problem

1. Add new project

2. Select Azure Functions project template

3. Set the name to be something with a period in the middle (i.e. "MyNamespace.MyFunctions")

4. Set the project as Startup Project

5. Ctrl-F5

#### Expected behavior

Looks for jobs

#### Actual behavior

```
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebScriptHostManager (DelegateActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> A host ID must be between 1 and 32 characters, contain only lowercase letters, numbers, and dashes, not start or end with a dash, and not contain consecutive dashes.
Parameter name: value (See inner exception for details.) ---> System.ArgumentException: A host ID must be between 1 and 32 characters, contain only lowercase letters, numbers, and dashes, not start or end with a dash, and not contain consecutive dashes.
Parameter name: value
   at Microsoft.Azure.WebJobs.JobHostConfiguration.set_HostId(String value)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.CreateScriptHostConfiguration(WebHostSettings settings)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.EnsureInitialized(WebHostSettings settings)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebHostResolver.GetWebScriptHostManager(WebHostSettings settings)
   at Microsoft.Azure.WebJobs.Script.WebHost.AutofacBootstrap.<>c__DisplayClass0_0.<Initialize>b__1(IComponentContext ct)
...
```

#### Known workarounds

Create a project name with no periods (i.e. "MyNamespaceMyFunctions")

#### Related information 

Actually adding an Azure Function to the project is unnecessary to repro this. The error insists that the issue is the Host ID (which I assume is the "id" property in "host.json", but no values have been found to work).

**Comment by lindydonna** [comment] 2016-12-02 21:34
Thanks for reporting!  This is a duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/1006. The "id" property is also not being picked up, as tracked here: https://github.com/Azure/azure-webjobs-sdk-script/issues/1007

**Closed by lindydonna** 2016-12-02 21:34 UTC
