### ISSUE TITLE
Continuous deployment from GitHub takes nearly 30 minutes

### ISSUE THREAD

**Issue by jhoerr** [Azure/azure-webjobs-sdk-script#1219] opened 2017-02-20 17:47 UTC
I'm deploying an F# function on the consumption plan and am using Paket for dependency management. . Deploying my project from GitHub takes nearly 30 minutes, with package restoration taking about 19 minutes.

I'm not able to run this function locally due to a number of CLI errors that I encounter and have not been able to resolve. As a result I can only use the browser to run/debug the function. As you might imagine this is pretty frustrating.

#### Repro steps

1. Create a new function app on consumption plan.
2. Clone/deploy https://github.com/jhoerr/iga-tracker-functions.

#### Expected behavior

The function is deployed reasonably quickly.

#### Actual behavior

The function is deployed very slowly.

#### Known workarounds

None.

#### Related information 

Source: https://github.com/jhoerr/iga-tracker-functions

**Comment by davidebbo** [comment] 2017-02-21 04:01
Please see https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues for initial steps to isolate.

Is it slow only on initial deployment, and then subsequent ones are faster? I would expect that unless what you're running ignores what's already installed.

**Comment by davidebbo** [comment] 2017-02-21 04:22
Fwiw, I just tried deploying your repo, and it took about 7 minutes, so much faster than what you saw. Not sure why the difference.

**Comment by davidebbo** [comment] 2017-02-21 04:39
After a no-op change, a subsequent deployment did take 30 minutes, but I think it's caused by the way your script is written. On the second deploy, there in now a packages folder in your repo folder, and the whole thing ends up getting copied to wwwroot, which I assume you don't need.

I think the root of the problem is that you are trying to use a post deploy action instead of taking over the deployment script. That would give you full control over everything that happens.

**Comment by jhoerr** [comment] 2017-02-21 13:47
> I think the root of the problem is that you are trying to use a post deploy action instead of taking over the deployment script. That would give you full control over everything that happens.

Ahh, OK. I didn't realize the later was an option. I was using some post-deploy Paket restore steps [documented here](http://kcieslak.io/Using-Paket-with-Azure-Functions). I'll look to see if this can be done during the deployment rather than after it and go from there.

As an aside, I've noticed that if I run `paket restore` from the in-browser dev console the folder populates within 1-2 minutes, as opposed to 15-20 minutes with the post-deploy script.

**Comment by davidebbo** [comment] 2017-02-21 15:07
To get started scripts (after doing one deployment), go to the Kudu UI and Tools / Download deployment script.

But it's puzzling that it would be faster from command line. My guess is that it's not quite running the same thing. It runs in the same identical sandbox, so everything else being equal, perf should match.

**Comment by jhoerr** [comment] 2017-02-23 20:19
I've got the paket restore worked into the build pipeline but I want to double-check that I'm ordering my operations properly. Would it be most appropriate to restore packages into the /repository folder before `KUDU_SYNC_CMD`, or by change the working directory to /wwwroot after `KUDU_SYNC_CMD` and restoring packages there instead? 

It might be a six/half-dozen situation; I just want to make sure I'm using the deployment script as you've intended.

**Comment by lindydonna** [comment] 2017-02-23 23:28
Closing this issue as it appears to be a configuration issue.

@davidebbo could you reply to the question about how to order commands in the deployment script?

**Comment by jhoerr** [comment] 2017-02-23 23:33
It's OK with me if you close it. I'll try to repro the problem again on a new app service with the improved build script and will re-open if it persists.

**Closed** 2017-02-23 23:39 UTC
