### ISSUE TITLE
Cron schedule resolution from app settings

### ISSUE THREAD

**Issue by jocawtho** [Azure/azure-webjobs-sdk-script#1168] opened 2017-01-31 20:12 UTC
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. in my function.json if i have %the-schedule% and i have an app setting called 'the-schedule'. At the start of the function i get the following error in the function logs:
2017-01-31T19:47:51.318 The following 1 functions are in error:
TimerTriggerNodeJS1: '%the-schedule%' is not a valid CRON expression.

#### Expected behavior

I think we should support this. I am writing a test for setting local timezones that requires this.

#### Actual behavior

error in function logs as follows:
2017-01-31T19:47:51.318 The following 1 functions are in error:
TimerTriggerNodeJS1: '%the-schedule%' is not a valid CRON expression.

**Comment by mathewc** [comment] 2017-01-31 20:59
This is a duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/181

**Closed by mathewc** 2017-01-31 20:59 UTC
