### ISSUE TITLE
TimerTrigger reliability issues

### ISSUE THREAD

**Issue by TheBlueSky** [Azure/azure-webjobs-sdk-script#239] opened 2016-04-09 08:16 UTC
Hello everyone,

I don't know if reliability is a known issue, given the early preview of the service, but I'm facing such issue constantly.

I have a `timerTrigger` function that runs every few minutes, and it's still under development. I change something, add some logs or functionality, then upload it. Suddenly, the function "decides" not to run at all... no errors, no logs, and not even "Function started" message.

The problem is I don't know when it happens and how (no repro unfortunately), and the bigger problem is I don't have a "Please Run" option or at least "What's Wrong" option.

Can someone help me troubleshoot such issue when it happens?

**Comment by mathewc** [comment] 2016-04-11 15:15
What language is your function? What happens when you hit the "Run" button which allows you to run the function on demand? When you say "upload it" you mean you're not editing via the portal?

**Comment by TheBlueSky** [comment] 2016-04-13 02:59
@mathewc, (1) I'm using Node.js, (2) haven't tried the "Run" button; maybe will have chance to try it the next time I face this issue, and (3) by "upload" I meant FTP, but I also edit via the portal when I want to tweak something or add debugging statements.

**Comment by christopheranderson** [comment] 2016-04-22 23:06
This still needs investigation. If you're not seeing this issue anymore please let us know.

**Comment by TheBlueSky** [comment] 2016-04-23 16:28
@christopheranderson, I'm still seeing this and tried again just now.
The function is scheduled to run every 3 minutes. I modified it at 20:05 and got the message that says something like "reloading because the function was updated". Immediately after that it run (before 20:06) and `myTimer.isPastDue` was true; however, the function didn't seem to complete and didn't print any error (the `context.log()` I have).
I tried updating the function and enabling/disabling it, but didn't get the "reloading" message, and the function didn't run again, until the writing of this.
In addition, when I run the function manually using "Run" button, I get "Status: 503 Service Unavailable", not in "Output" box, but above it and in red.
Although I tried my best to make sure it isn't my code that causes this, it still might be something with my code, but whatever the reason is, I'm stuck with no option to debug or restart the function, or no visibility on what's going on.

**Comment by christopheranderson** [comment] 2016-04-25 18:50
Could you share your code and the json from the "Advanced Editor" on the integrate tab? Does this repro when you create a new function with the same code and settings? It's not something I'm able to easily reproduce. It'd be really helpful to have a look at your code/settings.

**Comment by TheBlueSky** [comment] 2016-04-30 07:46
@christopheranderson unfortunately I can't share the code as it is, but will try to create something similar that reproduce the issue

**Comment by christopheranderson** [comment] 2016-04-30 19:18
That'd be great. Thanks! If you want to, you can also email me your function app name and I can look at the health of your functions from our backend as well. (chrande (at) microsoft (dot) com)

**Comment by mathewc** [comment] 2016-07-05 17:19
We need to try to repro this on current bits.

**Comment by brettsam** [comment] 2016-07-26 14:27
@TheBlueSky -- this issue is a couple of months old, have you continued having this problem?

**Comment by TheBlueSky** [comment] 2016-07-26 16:03
@brettsam, yes, last time I tries was less than 3 weeks ago. I had some time, so I tried create something that simulate the issue I have. However, I came across many issue that I eventually gave up.

- the editor does not allow me to copy and past.
- uploading files from the UI results to an  infinite Open File dialogs; whether I selected a file or cancelled.
- the function does not recompile after updating the script from UI.
- once I forgot to upload a referenced file; like in `require('./file.js');`, but even after I uploaded it later, the function is still not seeing it.
- I uploaded all the necessary NPM modules and I still receive "no such file or directory" for a file that is already there (part of some module).
- sometimes out of the blue, without modifications from my side, the function decides that "manybe I'm running too often" and starts showing service unavailable (when I click run button)... once I had to deleted the entire function app and recreate it because I couldn't find a way to get rid of this error.
- there are no troubleshooting or detailed log that shows why the function doesn't run on schedule, why it doesn't run at all, why doesn't recompile, and many other whys.

Those are just few that I encountered maybe in an hour trying to create a repro for this issue.

**Comment by brettsam** [comment] 2016-08-09 19:14
Sorry you ran into so many issues. A couple follow-ups --
- If you weren't able to copy/paste in the editor, that may be a bug. What browser were you using?
- When you say you were uploading files in the UI -- which UI were you using?
- If you have an example of the script and the npm modules that were giving you problems, could you share those?

**Comment by TheBlueSky** [comment] 2016-08-13 16:42
Hello @brettsam.

* I tries in both, Edge and Chrome. I didn't face this issue that often and today I tried again and I was able to copy and paste. It's either me or Azure Functions were having a bad day at the time :)
* Under the Function editor, "Code", there is an option that says "View files". When clicking this option, the list of files appears with 2 buttons beneath it. The right one is the one I meant.
* You can see [here](https://gist.github.com/TheBlueSky/e73ff23a8bcadc304184017d13adb4f6) a sample similar (in some way) to what I'm trying to do. Well, I'm not really trying to scrape Bing results; it's just a close enough sample.  See below the result of executing the function (that I provided the code for) in a 3-min schedule. As you can notice, the function ran once successfully, run the second time without completing, and then nothing happened until I gave up and disabled it (more than 20 minutes later). 
```
    2016-08-13T15:37:50  Welcome, you are now connected to log-streaming service.
    2016-08-13T15:38:50  No new trace in the past 1 min(s).
    2016-08-13T15:39:00.025 Function started (Id=c2f28c3f-2be8-4225-bb99-8107944e540a)
    2016-08-13T15:39:01.057 http://www.bing.com/search?q=azure+functions
    2016-08-13T15:39:01.572 completed
    2016-08-13T15:39:01.666 Function completed (Success, Id=c2f28c3f-2be8-4225-bb99-8107944e540a)
    2016-08-13T15:40:50  No new trace in the past 1 min(s).
    2016-08-13T15:41:50  No new trace in the past 2 min(s).
    2016-08-13T15:42:00.005 Function started (Id=84524e3c-84ec-4a5c-b6fa-dfe688478dc5)
    2016-08-13T15:42:00.005 http://www.bing.com/search?q=azure+functions
    2016-08-13T15:43:50  No new trace in the past 1 min(s).
    2016-08-13T15:44:50  No new trace in the past 2 min(s).
    2016-08-13T15:45:50  No new trace in the past 3 min(s).
    2016-08-13T15:46:50  No new trace in the past 4 min(s).
    2016-08-13T15:47:50  No new trace in the past 5 min(s).
    ....
```
Hope this helps.

**Comment by brettsam** [comment] 2016-09-08 20:43
Sorry it took me so long to get back to this. I looked at your code and there's a couple of things that explain what you're seeing:

1. `completedCount` is a global variable. That means that every time the function runs, it's being incremented. And since you're checking for it to equal `urls.length`, it ends up working once and then never again (because it's greater than that now). If you add something like `context.log(completedCount);` inside your polling code, you can see that it never goes back to 0 (unless the host restarts).
2. Also, you're using `setTimeout` to check for completion. That will only ever run once -- I think you meant to use `setInterval`. And then you'd need to use `clearInterval` to stop it from running forever.

I think with these two things fixed everything should run as expected.

**Comment by brettsam** [comment] 2016-09-14 13:01
Closing this for now. If you continue to see issues, feel free to re-open and I'll take a deeper look. Thanks for the feedback!

**Closed by brettsam** 2016-09-14 13:01 UTC
Labels: bug, in progress

**Comment by TheBlueSky** [comment] 2016-09-16 06:18
@brettsam thanks for your assist and sorry for bothering you with my own bugs :)

For the other issue, I'll try to reproduce again when I have time and open new Issues when needed.
