### ISSUE TITLE
Add project.lock.json file to .gitignore

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#800] opened 2016-10-23 05:44 UTC
If the lock file is committed, it won't trigger a nuget restore. We should include ignoring it in the .gitignore.

**Comment by fabiocav** [comment] 2016-10-23 07:29
Yes. This is by design. @lindydonna captured the .gitignore item in her latest proposal and *might* already have an issue (Donna?)

**Comment by lindydonna** [comment] 2016-10-24 16:56
Duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/775

**Closed by lindydonna** 2016-10-24 16:56 UTC
Labels: CLI
