### ISSUE TITLE
Precompiled Azure Function's dll will be lock on deployment

### ISSUE THREAD

**Issue by guitarrapc** [Azure/azure-webjobs-sdk-script#1105] opened 2017-01-10 19:53 UTC
Precompiled AzureFunction is very useful for Intellisense friendly development. However, it's dll will be locked by w3wp.exe. This required me to kill w3wp then restart AppService to swap with new dll.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create Precompiled AzureFunctions.

2. Deploy to AzureFunctions.

3. Verify it works and modifies the source code, then re-deploy. New code will not be affected until you kill w3wp and restart AppService.

#### Expected behavior

New source code's dll should replace without kill w3wp and Restart AppService.

#### Actual behavior

dll is locked and new source code will not be work until kill, restart.

#### Known workarounds

Kill w3wp.exe and restart AppService.

#### Related information 

Use https://github.com/guitarrapc/AzureFunctionsIntroduction for a sample.

**Comment by lindydonna** [comment] 2017-01-31 19:55
@guitarrapc To avoid the locked file problem, you can add the app setting `MSDEPLOY_RENAME_LOCKED_FILES` with value of `1`. However, you still have to restart the Function App.

So, this is a duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/1023.

**Comment by guitarrapc** [comment] 2017-02-01 00:15
@lindydonna Thanks. Yes I do know it. But the core issue is Host restart required as you describe. I will keep watch duplicate issue.

**Comment by fabiocav** [comment] 2017-02-01 02:48
This is slightly different, though, so I'm reopening. The good thing is that both will be addressed by the same PR.

**Comment by guitarrapc** [comment] 2017-02-01 15:23
It's awesome news!! Appreciate for greate work.

**Closed** 2017-02-06 17:33 UTC
Labels: duplicate, improvement, in progress
