### ISSUE TITLE
error FS39: The value or constructor '{functionName}' is not defined 

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk-script#719] opened 2016-09-23 12:38 UTC
Hi,

I'm getting an error FS39: The value or constructor '{functionName}' is not defined if {functionName} is in a separate file that is brought in via the #load command.

I'm following instructions via Reusing .fsx code - https://azure.microsoft.com/en-gb/documentation/articles/functions-reference-fsharp/

**api-function-do-struff\run.fsx**

```
...
#load "..\Shared\ParameterUtil.fsx"
let json = generateJson(input)         <---error FS39: The value or constructor 'generateJson' is not defined
...
```

**Shared\ParameterUtil.fsx**

```
...
let generateJson (input:string) = 
    input
...
```

I have observed similar issues when containing types that inherit from TableEntity that too are in a separate file and brought in via #load command.

**Workaround**

```
...
let json = ParameterUtil.generateJson(input)
...
```

Warmest regards,

Garrard.

**Comment by lindydonna** [comment] 2016-09-26 22:18
@fabiocav please investigate and we can re-triage if needed

**Comment by brettsam** [comment] 2016-10-18 17:34
@soninaren -- can you see if this still repros with the latest bits?

**Comment by dsyme** [comment] 2016-11-07 17:58
@garrardkitchen This is by design. You need to qualify the function by the module name. To avoid that, use ``[<AutoOpen>]`` on the module in the file you are loading

**Comment by dsyme** [comment] 2016-11-07 17:59
@lindydonna  @christopheranderson Please close this, thanks (if you like, add @sylvanc and myself as issue-maintainers to this repo so we can close/tag F#-related issues)

**Closed** 2016-11-14 18:07 UTC
Labels: bug, lang-F#, rc:should-have
