### ISSUE TITLE
C#: Extract binding data for HttpTrigger

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#230] opened 2016-04-07 00:15 UTC
I have a Table Input expecting `UserId` in the bindingData passed to it from the HTTP Trigger's HTTP Body. We're not properly passing the data along, it seems.

Error:

```
Exception while executing function: Functions.HttpTriggerCSharp2. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'inputBlob'. Microsoft.Azure.WebJobs.Host: Value cannot be null.
Parameter name: bindingData.
```

Code:
```C#
using System.Net;
using System.Threading.Tasks;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, string inputBlob, TraceWriter log)
{
    log.Verbose($"C# HTTP trigger function processed a request. RequestUri={req.RequestUri}");
    log.Verbose(inputBlob);
    // parse query parameter
    string name = req.GetQueryNameValuePairs()
        .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
        .Value;

    // Get request body
    dynamic data = await req.Content.ReadAsAsync<object>();

    // Set name to query string or body data
    name = name ?? data?.name;

    return name == null
        ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
        : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
}
```

function.json

```json
{
  "bindings": [
    {
      "webHookType": "",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "name": "res",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "inputBlob",
      "type": "blob",
      "path": "user-info/{UserId}.json",
      "connection": "<app setting>",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

**Comment by mathewc** [comment] 2016-04-07 01:52
Isn't this a duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/180?

Anyhow, yes, the Table binding needs work and I'll get to it soon.

**Comment by mathewc** [comment] 2016-04-11 22:55
The issue here is that unlike all of our other trigger bindings, the HttpTrigger is not an SDK core (or extension) binding. So it will not be known to the SDK binding pipeline - it does not populate any binding data.

**Comment by mathewc** [comment] 2016-04-19 23:28
I've addressed this for Node, since in that binding pipeline it was easy to support, since we were already doing it for all the other non HTTP binding types.

To get this working for C# will require more work. Some options have been discussed.

**Comment by christopheranderson** [comment] 2016-06-21 18:29
RC Justification: language/binding consistency

**Comment by fabiocav** [comment] 2016-08-10 01:02
Removing from the current milestone and re-assigning this to @mathewc as this will be addressed by a new (proper) HTTP binding.

**Comment by mathewc** [comment] 2016-08-15 19:35
Resolved by https://github.com/Azure/azure-webjobs-sdk-script/pull/568

**Closed by mathewc** 2016-08-15 19:35 UTC
Labels: bug
