### ISSUE TITLE
Access certificates from an Azure Function when using the Consumption plan

### ISSUE THREAD

**Issue by henning-krause** [Azure/azure-webjobs-sdk-script#1032] opened 2016-12-07 13:48 UTC
When creating an Azure Function using the App Service Plan, I can get access to uploaded certificates by setting the AppSetting WEBSITE_LOAD_CERTIFICATES="*".

However, this does not work in consumption mode. 

Are different steps required in this scenario or is this unsupported?

If the latter is the case, when will this be supported?

**Comment by mathewc** [comment] 2016-12-07 16:25
Duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/538. Thanks for logging :)

**Closed by mathewc** 2016-12-07 16:25 UTC

**Comment by natasha-tahariya** [comment] 2018-01-06 13:41
Hi, 

I am facing an issue when trying to access a certificate in consumption plan function app. I have uploaded the certificate from SSL tab. and added the setting WEBSITE_LOAD_CERTIFICATES = * in Application settings. But still getting error that certificate with thumbprint is not found. The same code is working in local.

this is the code i am using in Function app to get certificate - 

   public static object GetCertificate(string thumbPrint)
        {
            X509Store store = null;
            try
            {
                store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
                store.Open(OpenFlags.OpenExistingOnly | OpenFlags.ReadOnly);

                var certs = store.Certificates.Find(X509FindType.FindByThumbprint, thumbPrint, true);

                if (certs.Count == 1)
                {
                    var cert = certs[0];
                    return cert;
                }
                else
                {
                    throw new Exception($"Certificate with thumbprint {thumbPrint} not found");
                }

            }
            finally
            {
                if (store != null)
                    store.Close();
            }
        }

Can you please let me know what i am missing
