### ISSUE TITLE
Timer trigger can fire almost a minute early when using custom timezone

### ISSUE THREAD

**Issue by cincuranet** [Azure/azure-webjobs-sdk-script#995] opened 2016-11-28 11:51 UTC
Running a function based on timer trigger triggers it before the scheduled time. My function is scheduled to run exactly at 0 minutes and 0 seconds (though I don't care about seconds being few seconds off, that's expected), but it's often executed ~50s _before_ the scheduled time. I'm using custom timezone for Function App.

Here's the screenshot.
![img](https://cloud.githubusercontent.com/assets/4540597/20667377/3d3b062a-b569-11e6-860d-86bf3537058c.png)

**Comment by davidebbo** [comment] 2016-11-28 15:48
I changed the title to better reflect the issue. SPecifically, in your case you had set `APPSETTING_WEBSITE_TIME_ZONE = Central Europe Standard Time`.

I suspect there is some kind of DateTime bug in that code, possibly related to our use of NCronTab.

**Comment by lindydonna** [comment] 2016-11-28 19:49
Assigning @davidebbo for investigation. After that, we should either hard fail or fix the issue.

**Comment by davidebbo** [comment] 2016-11-30 17:49
We confirmed on [this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/279da6af-44a3-407b-b0f9-94873a7e5b8f/function-not-being-triggered-according-to-schedule?forum=AzureFunctions) that the issue went away after removing the local time zone.

I discussed with Mathew, who will take the next step.

**Comment by mathewc** [comment] 2016-12-13 23:06
We believe this issue is caused by a mismatch in timezone between our scale controller and the Functions runtime. E.g. the Function App is configured to use a custom timezone, however the scale controller is using UTC meaning the app isn't woken up at the right time.

@cgillum Is tracking an issue in the scale controller for this. When that is fixed we'll verify end to end with this exact repro and make sure things work.

**Comment by jocawtho** [comment] 2017-01-18 19:03
Currently testing a fix for this. Will update here when submitted.

**Comment by haefele** [comment] 2017-01-20 10:31
I believe that I ran into the same issue.
My function should've run at 7.30 AM (cron expression is "0 30 7 * * *") and the time-zone is "W. Europe Standard Time".
But it did not get executed.

**Comment by davidebbo** [comment] 2017-01-20 16:15
@haefele the fix has not yet been deployed, so that is expected.

**Comment by jocawtho** [comment] 2017-02-01 19:04
Update submitted. It will go out with our current deployment and should be fully available in the next two weeks!

**Comment by davidebbo** [comment] 2017-02-17 17:16
The fix for this is about another week out (will deploy gradually until then).

**Comment by davidebbo** [comment] 2017-02-28 15:58
The fix is not deployed everywhere (actually has been for a few days).

**Closed by davidebbo** 2017-02-28 15:58 UTC

**Comment by lindydonna** [comment] 2017-02-28 22:27
@davidebbo I think you had a typo: the fix is **now** deployed everywhere. :)

**Comment by davidebbo** [comment] 2017-02-28 22:27
Duh, fixed, thanks!
