### ISSUE TITLE
Assembly.Location of private assembly is empty when load from bin folder.

### ISSUE THREAD

**Issue by iwate** [Azure/azure-webjobs-sdk-script#1233] opened 2017-02-24 04:21 UTC
User can not get location of private assemblies. It's always empty string.

#### Repro steps

1. Create C# function.

2. Upload private assemblies to bin folder.

3. Load assembliy by using `#r`

4. Get `typeof({Any class of private assembliy}).Assembly.Location` 

#### Expected behavior

Assembly.Location == @"D:\home\site\wwwroot\\{FunctionName}\bin\\{AssemblyName}.dll"

#### Actual behavior

Assembly.Location == string.Empty

#### Known workarounds

Now, private assemblies are loaded using by `Load(Byte[])` and this is the reason.

> If the assembly is loaded from a byte array, such as when using the Load(Byte[]) method overload, the value returned is an empty string ("").
> https://msdn.microsoft.com/ja-jp/library/system.reflection.assembly.location(v=vs.110).aspx

Recently, Function was changed to using shadow copy.(https://github.com/Azure/azure-webjobs-sdk-script/pull/1169)
This changes solved some problems. for example assembly lock.
Therefore, I think that there is no problem with `FunctionMetadataResolver` using `Assembly.LoadFrom(String)` for loading private assemblies. 

#### Related information 

Private assemblies are loaded by FunctionMetadataResolver.
https://github.com/Azure/azure-webjobs-sdk-script/blob/661e8de8449865139d20fe019f789a65cfe5da33/src/WebJobs.Script/Description/DotNet/FunctionMetadataResolver.cs
```
public Assembly ResolveAssembly(string assemblyName)
{
    Assembly assembly = null;
    string assemblyPath = null;

    if (_externalReferences.TryGetValue(assemblyName, out assemblyPath))
    {
        // When loading shared assemblies, load into the load-from context and load assembly dependencies
        assembly = Assembly.LoadFrom(assemblyPath);
    }
    else if (TryResolvePrivateAssembly(assemblyName, out assemblyPath))
    {
        /* THIS CODE IS THIS ISSUE'S POINT */
        assembly = Assembly.Load(File.ReadAllBytes(assemblyPath));
        assembly.MapCodeBase(assemblyPath);
    }
    else if (_packageAssemblyResolver.TryResolveAssembly(assemblyName, out assemblyPath))
    {
        // Use LoadFile here to load into the correct context
        assembly = Assembly.LoadFile(assemblyPath);
    }

    return assembly;
}
```

**Comment by fabiocav** [comment] 2017-02-24 17:58
This is a known limitation at this point and the behavior is by design.  Private assemblies are loaded from bytes to avoid other issues, beyond assembly file locking, but some of those issues (e.g. in place updates with same assembly identity) were addressed with recent runtime changes as well, one of them being the auto-restart.

Private assemblies (assemblies in the function's `bin` folder) are **not** loaded in the load-from context (they're loaded with 'No Context'), this is an important distinction and enables scenarios like loading different assemblies with the same identity by different functions and others, so we **could not** use `LoadFrom` as that would be a breaking change in behavior. This also means that private assemblies would not benefit from the new shadow copy feature, as they're not loaded through fusion.

If that information is important to you, the current alternative is to use shared assemblies (e.g. create a `sharedbin` folder in `wwwroot` and reference the assemblies from your function using `#r "..\sharedbin\myassembly.dll"`).

**Comment by iwate** [comment] 2017-02-25 05:13
@fabiocav, Thank you for your answer and I understand the reason:)



Followings are supplementary explanation.

Already, I create `appbin` folder in function folder.(D:\home\site\wwwroot\{FunctionName}\appbin\).
And upload my assemblies.(D:\home\site\wwwroot\{FunctionName}\appbin\{MyAssemblies}).
I think this behavior is same to `../sharebin`

However, I sometimes faced the problem that cannot get location.
Then, I thought that it's good for all to get `Location` from private assemblies(if so, I don't have to create appbin folder) but I was thoughtless.

If I get more detail for that sometimes cannot get shared assemblies location, I report it as other issue.

Thank you.

**Comment by fabiocav** [comment] 2017-02-27 19:03
Thank you @iwate! I appreciate the additional details.

I'll close this but please do let us know if you run into that with shared assemblies as that should definitely not be the case.

**Closed by fabiocav** 2017-02-27 19:03 UTC
