### ISSUE TITLE
eventHubTrigger with bad connection string brings down the whole host

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#109] opened 2016-03-16 16:23 UTC
The default IoT sample has:

```json
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "myEventHubTrigger",
      "direction": "in",
      "path": "samples-workitems",
      "connectionString": "<your EventHub receiving connection string here>"
    }
  ]
}
```

Instead of getting a function level error, it brings down the whole host and nothing else can run:

```
2016-03-16T16:20:00 A ScriptHost error occurred
2016-03-16T16:20:00 System.Configuration.ConfigurationErrorsException: The Service Bus connection string is not of the expected format. Either there are unexpected properties within the string or the format is incorrect. Please check the string before trying again.
   at Microsoft.ServiceBus.Messaging.Configuration.KeyValueConfigurationManager.CreateNameValueCollectionFromConnectionString(String connectionString)
   at Microsoft.ServiceBus.Messaging.Configuration.KeyValueConfigurationManager.Initialize(String connection, Nullable`1 transportType)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.CreateAmqpConnectionString(String eventHubConnectionString)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.DefaultEventHubClientFactory(String eventHubConnectionString, EventProcessorOptions processorOptions)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.<>c__DisplayClass4.<.ctor>b__0(EventProcessorOptions o)
   at Microsoft.ServiceBus.Messaging.EventProcessorHost.<InitializeAsync>d__b.MoveNext()
```

**Comment by mathewc** [comment] 2016-03-16 16:48
This a dupe of existing issue https://github.com/Azure/azure-webjobs-sdk-script/issues/71. I've been thinking of a way to handle this and make them function level errors, but it will require core SDK work.

**Comment by fabiocav** [comment] 2016-03-16 17:13
@mathewc I'd love to chat about what you have in mind as #71 is the next thing I'll be tackling.

**Comment by mathewc** [comment] 2016-03-16 17:17
#71 is probably something for me to tackle first.

**Comment by fabiocav** [comment] 2016-03-16 17:21
Sounds good. I'll clear the issue assignment.

**Comment by mathewc** [comment] 2016-03-18 02:29
Fixed via https://github.com/Azure/azure-webjobs-sdk-script/commit/333d05ac3e31f4dc16ee4b4913b6e5fa83f9353c.

**Closed by mathewc** 2016-03-18 02:29 UTC

**Comment by gideondsouza** [comment] 2017-12-19 14:51
hi, I know this isn't so much the place for this, however msdn seems to be almost useless.
What is a IOT connection string supposed to be like? I have something like this 
HostName=iothub-name.azure-devices.net;DeviceId=CSxxxxxX;SharedAccessKey=[key] } 
Could someone please help out and I'm really stuck here.
