### ISSUE TITLE
Better support for async functions with ServiceBus out bindings

### ISSUE THREAD

**Issue by mthierba** [Azure/azure-webjobs-sdk-script#991] opened 2016-11-26 20:16 UTC
Currently, ServiceBus messages can only be sent out of an **async** function using the `IAsyncCollector<T>` binding.

I am specifically using ServiceBus bindings (as opposed to storage queues) in order to be able to schedule those messages to be enqueued at some defined point in the future. That, however, requires direct access to the `BrokeredMessage` which is only supported via the `out BrokeredMessage` binding in Functions.

The latter is incompatible with async functions, so one ends up with pretty ugly code when using async-only APIs (HttpClient).

I would like to able to bind a ServiceBus queue to a `QueueClient` paramter (similar to `CloudBlockBlob` _inout_ bindings) to overcome that limitation.

**Comment by lindydonna** [comment] 2016-11-28 19:43
Could you provide the exact code you're trying and the behavior you'd like to see?

**Comment by mthierba** [comment] 2016-11-28 22:43
@lindydonna - Sure, this is what I'd like to be able to write:

```
#r "Microsoft.ServiceBus"

using System.Net;
using Microsoft.ServiceBus.Messaging;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, QueueClient queue, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");

    // parse query parameter
    string name = req.GetQueryNameValuePairs()
        .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
        .Value;

    // Get request body
    dynamic data = await req.Content.ReadAsAsync<object>();

    // Set name to query string or body data
    name = name ?? data?.name;

    var scheduledMessage = new BrokeredMessage(name)
    {
	   ScheduledEnqueueTimeUtc = DateTime.UtcNow.AddDays(7)
    };
    await queue.SendAsync(scheduledMessage);
    
    return name == null
        ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
        : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
}
```

The only ServiceBus binding type currently supported in async functions is `IAsyncCollector<T>` which for this example is insufficient as it doesn't give access to the `BrokeredMessage` itself.

A real-world example where I've hit that limitation is using a Function to manage _outlook.office.com_ push notification subscriptions. Those are only valid for up to seven days, and need to be renewed before their expiration.

What I'm doing is to have a Function triggered by a ServiceBus message that is scheduled to be enqueued just before the subscription expiration. The Function then performs the renewal (a REST call) and eventually schedules a new ServiceBus message for when the next renewal is due.

Since this is using HttpClient, the most natural paradigm to use for this would be an async function (in C#, at least). However, that is currently not possible.

This particular example might or might not be an obscure edge case, I don't know. Making `QueueClient` available as a binding parameter, however, would be the conceptual equivalent of `CloudTable`, `CloudQueue`, and `CloudBlockBlob` - all already available for storage account bindings where more control is desired.

Looking forward to your thoughts.

**Comment by lindydonna** [comment] 2016-11-28 23:21
@mathewc Any thoughts?  The problem is that `IAsyncCollector<T>` doesn't provide access to `BrokeredMessage`. Is there potential for a more targeted fix here?

**Comment by mthierba** [comment] 2016-11-29 11:37
I should note that supporting a `IAsyncCollector<BrokeredMessage>` binding _would_ achieve the same goal. That might be easier to achieve. But it still wouldn't put ServiceBus at full parity with the storage account bindings (flexibility-wise).

**Comment by fabiocav** [comment] 2016-11-29 18:19
@mthierba , `IAsyncCollector<BrokeredMessage>` **is** supported by the binding. What issues did you run into when trying to use it?

**Comment by mthierba** [comment] 2016-11-29 19:40
@fabiocav - I didn't actually try it as this only just occurred to me in the course of responding to this issue! This is great news indeed - I literally just went ahead and converted a whole bunch of functions accordingly... These gh issues are more and more becoming _Azure Functions - The Missing Documentation_. Hope others will find this and avoid falling down the same rabbit hole.

Many thanks! Unless you will want to consider implementing what I had originally asked for - feel free to close this issue now.

**Comment by fabiocav** [comment] 2016-12-03 02:07
Closing this for now as the issue is resolved. Please open an issue if you feel the requested feature is important.

**Closed by fabiocav** 2016-12-03 02:07 UTC
