### ISSUE TITLE
NullReferenceException during starting script host when a type is null

### ISSUE THREAD

**Issue by andriysavin** [Azure/azure-webjobs-sdk-script#2004] opened 2017-10-06 21:08 UTC
This line stores loaded type from function library:
https://github.com/Azure/azure-webjobs-sdk-script/blob/e327dfda457019e549033342ba3b26b7a8059713/src/WebJobs.Script/Host/ScriptHost.cs#L639

However, its totally possible that the type will fail to load and variable will be assigned with null. In my case this happens due to famous "System.Runtime.dll 4.1.1.0 can't be found" when loading a type. Since the code is sure the type will never be null, we get NullReferenceException little later, which tells me nothing about real problem.

**Comment by paulbatum** [comment] 2018-01-19 23:57
I believe this is a dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/1867, with a fix committed just a little before you filed the issue. 

Here is the null ref check:

https://github.com/Azure/azure-webjobs-sdk-script/blob/452b544e72eeb9a757c61c58882f153027570b1c/src/WebJobs.Script/Host/ScriptHost.cs#L608-#L612

I confirmed this fix was made for both functions v1 and v2.

The fix was probably not deployed at the time you were encountering it. Please reopen and/or comment if you are still seeing this.

**Closed by paulbatum** 2018-01-19 23:57 UTC
Labels: bug
