### ISSUE TITLE
C#: Can't use CloudBlockBlob as input parameter

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#89] opened 2016-03-12 00:47 UTC
I want to use a CloudBlockBlob as a binding parameter, but I get an exception from the function script host when I try to do this.

C# function: 
```
public static void Run(CloudBlockBlob blobInput, TraceWriter log)
```
Binding:

```
{
    "bindings": [
        {
            "type": "queueTrigger",
            "direction": "in",
            "queueName": "resizerequest"
        },
        {
            "type": "blob",
            "name": "blobInput",
            "direction": "in",
            "path": "{BlobNameLG}/{FileName}"
        }
    ]
}
```

Then, in the log stream, I see this:

```
System.InvalidOperationException: Cannot bind blob to CloudBlockBlob using access Read.
at Microsoft.Azure.WebJobs.Host.Blobs.ConverterArgumentBindingProvider`1.TryCreate(ParameterInfo parameter, Nullable`1 access)
...
```
I see the same issue if I try to do an output binding with CloudBlockBlob. A Stream binding seems to work fine, however.

**Comment by mathewc** [comment] 2016-03-12 01:33
Supported bindings are detailed here: http://go.microsoft.com/fwlink/?LinkID=524028&clcid=0x409

Likely the issue is we're only binding BlobAttribute using FileAccess.Read (the default), not taking the binding direction into account. If CloudBlockBlob only supports RW as the PDF indicates, we probably need to have direction=inout, and when we bind, we interpret that as FileAccess.ReadWrite

**Comment by fabiocav** [comment] 2016-04-05 04:28
Changing this from bug to feature for accuracy, as the issue is due to a limitation on the current supported binding access/directions.

**Comment by mathewc** [comment] 2016-04-05 04:34
Can you elaborate on that? We have some other issues related to in/out support - wondering if this is related.

**Comment by fabiocav** [comment] 2016-04-05 05:08
We don't currently support Read/Write access, which is what the Blob binding requires in order to work with `ICloudBlob`,`CloudBlockBlob` and `CloudPageBlob`. Right now, the supported binding direction is either In or Out. We'd either need to support InOut, or when appropriate, use ReadWrite for the binding based on the argument type (e.g. use ReadWrite for the blob binding if the type is `ICloudBlob`,`CloudBlockBlob` and `CloudPageBlob`).
You're more familiar with that process; any concerns about trying automatically treat the binding as RW in those cases?

**Comment by fabiocav** [comment] 2016-04-06 20:59
@mathewc any feedback on the approach described in my last message? This is something we can do pretty easily if there are no objections to that approach.

**Comment by mathewc** [comment] 2016-04-06 21:01
There is a BindingDirection.InOut, it's just not plumbed everywhere correctly. What is your proposal? Note we have another issue tracking that work across the languages/bindings.

**Comment by fabiocav** [comment] 2016-04-06 21:05
Somehow, I missed that InOut was there. My proposal was to treat the RW types (as, unless I'm mistaken, they seem to support RW only) as InOut/RW. That would be easy to do when building the custom attribute, but it would only apply to C# at the moment. I would rather wait for proper InOut support if that's in the plans.

**Comment by mathewc** [comment] 2016-04-06 22:28
https://github.com/Azure/azure-webjobs-sdk-script/issues/49

**Comment by fabiocav** [comment] 2016-04-06 22:32
I know we want to have consistency across the different languages, but for C#, we could easily enable this scenario in an "advanced" mode by manually modifying the `function.json` to use `InOut` when applicable and properly handle that when generating the custom attributes. 
Thoughts?

**Comment by fabiocav** [comment] 2016-05-12 17:42
This has been resolved by:
https://github.com/Azure/azure-webjobs-sdk-script/pull/299

**Closed** 2016-05-12 17:42 UTC
Labels: feature, lang-c#

**Comment by lindydonna** [comment] 2016-05-13 17:47
Awesome! Could you let me know when the fix is in staging or prod?
