### ISSUE TITLE
Function not recompiled when changed

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#431] opened 2016-06-10 17:45 UTC
Creating this to track [this ](https://github.com/Azure/azure-webjobs-sdk-script/issues/429#issuecomment-225197842) comment on issue #429

**Comment by fabiocav** [comment] 2016-06-10 17:46
@kmh0237, I'm creating this issue here so we can track the problem you've reported.

**Comment by fabiocav** [comment] 2016-06-10 17:48
One quick question, if you create a Node function (e.g. an HttpTrigger Node function), do you see the "Reloading" message in the log? 
You may need to run the function before making changes in order to trigger the reload, and the message would be similar to this:
`Script for function 'HttpTriggerNodeJS1' changed. Reloading.`

**Comment by kmh0237** [comment] 2016-06-10 18:57
Okay, I created a node function like you specified, the url is https://seedpro-fn-dev.azurewebsites.net/api/HttpTriggerNodeJS1?code=lm9ee6m4odo594op83el5l8fre7ap6t83fsewcrie6hizr529w8tdwtgho17f8fqagyom9529.

Using the default code:
module.exports = function(context, req) {
    context.log('Node.js HTTP trigger function processed a request. RequestUri=%s', req.originalUrl);

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};

This has the same bug (I think?) where when I make a change, it does not recognize the change.  That is to say, I only see the 'Script for function 'HttpTriggerNodeJS1' changed. Reloading.' message never shows up for this job no matter how or when I change it.  When I click the "Run" button it gives me a status 401 Unauthorized "Authentication is enabled for the function app. Disable authentication before running the function."  This message is likely because of all the security around our functions.

I was seeing something similar with the C# function where it wouldn't reload, except for it did show the reloading message but only when there was an error in the run.csx.  Do you expect it not to reload if it hasn't ever been run?  That seems strange to me.

**Comment by fabiocav** [comment] 2016-06-10 20:16
For Node, functions are lazily loaded, meaning that if a function is changed but hasn't been loaded for execution, it won't trigger a reload. That's why having the "run" step between changes would help us test that behavior.

**Comment by kmh0237** [comment] 2016-06-10 20:58
I'm working with my team to try to get it to run with authentication enabled on our function app (because we don't want to disable it for just anyone to use).  We're trying to use a post to the function url with a bearer token, but that just returns a 503 right now.  This is strange because when I send an older bearer token that's expired, it instead redirects me to the login page.  Am I even trying to run this properly?  Once I can get ahold of some of our Azure admins and get some of the function to be runnnable, I'll let you know.

Does it make sense to not allow functions to be runnable from the function GUI when authentication is enabled?  That is making this a lot more difficult for me (the "Authentication is enabled for the function app. Disable authentication before running the function." error).  Which is wierd because I'm logged in as a user that should be authorized to use the function (especially given that I'm editing them at that point!)

**Comment by kmh0237** [comment] 2016-06-13 16:01
I've talked to my tech lead, and we haven't found a way to get the manual triggers to work with node functions.  Under "Configure Authentication", we have "App Service Authentication" set to "Yes" and "Action to take when request is not authenticated" set to "Log in with Azure Active Directory."  We don't want to change these settings because it provides security for our functions, however we believe this is what is causing that authentication error I mentioned earlier.  I'm sorry, but I can't run the node job manually to help you debug this unless there is a way to do that while still having authenticated functions.

Also, as an update about the original issue (with C# functions not recompiling), I found out that in rare cases when I refresh it will suddenly start working with everything recompiling properly, then the next time I refresh the issue is back and it won't recompile no matter what I modify.  So the issue is very inconsistent.  More often than not, though, a refresh will result in a non-compiling version of the C# function.

**Comment by fabiocav** [comment] 2016-07-06 16:20
@kmh0237 are you still experiencing this issue?

**Comment by kmh0237** [comment] 2016-07-11 20:53
Yes, I still see this issue.  In the function log, it only logs a recompile attempt when there are errors in the run.csx file.  We are no longer going to use azure at the moment, but I can still give you easily accessible details on the bug we found.

**Comment by fabiocav** [comment] 2016-07-11 21:31
@kmh0237 is it feasible to setup a repo with your function code (metadata and code) and place the log files there as well? I haven't been able to repro this and want to take a look at your setup and logs to see if we can identify the root. Also, did you experience this with other function apps as well (new/different Azure Functions sites)?

**Comment by fabiocav** [comment] 2016-08-09 18:44
Removing from the current iteration. Will assign once the work is identified.

**Comment by christopheranderson** [comment] 2016-08-15 22:19
Without repro, closing this for now

**Closed by christopheranderson** 2016-08-15 22:19 UTC
Labels: bug

**Comment by webtechy** [comment] 2017-01-12 23:09
Am currently seeing this issue I believe.

**Comment by ShayanZafar** [comment] 2017-06-09 21:09
i am getting this bug.

**Comment by fabiocav** [comment] 2017-06-10 00:26
@ShayanZafar this has been closed and the there have been a significant number of changes in this area since then. Can you please open another issue with a detailed description of what you're seeing and, if possible, your function app name?

**Comment by ShayanZafar** [comment] 2017-06-12 05:34
I restarted the app and it fixed my issue. I guess that's a workaround.

**Comment by ShayanZafar** [comment] 2017-07-26 03:05
I created a Javascript app, ran npm in the function directory, required the dependency and saved the app. The message says Reloading... but i don't see a compile succeeded? is there something i need to do to get this js function to compile in Node?
