### ISSUE TITLE
scripthost no longer recognizing functions

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#321] opened 2016-05-01 03:45 UTC
Hi,

Today, using installation option #2, I  upgraded to the latest script host. Unfortunately, no functions are picked up. I have to revert back to v1.0.0-alpha1-10127 to get it working again. I do see the following error in the logs when using anything greater than v1.0.0-alpha1-10127:

```
[05/01/2016 02:32:36 > aaaf25: SYS WARN] Failed to diff WebJob directories for changes. Continuing to copy WebJob binaries (this will not affect the WebJob run)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\local\Temp\jobs\continuous\scripthost\r1rcvrpv.jji'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.Abstractions.DirectoryInfoWrapper.GetFiles(String searchPattern, SearchOption searchOption)
   at Kudu.Core.Jobs.BaseJobRunner.GetJobDirectoryFileMap(String sourceDirectory)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)
[05/01/2016 02:32:36 > aaaf25: SYS ERR ] Failed to copy job files: System.Threading.ThreadAbortException: Thread was being aborted.
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(JobBase job, IJobLogger logger)
[05/01/2016 02:32:56 > aaaf25: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
[05/01/2016 02:32:56 > aaaf25: SYS INFO] Status changed to Running
[05/01/2016 02:32:56 > aaaf25: INFO] 
[05/01/2016 02:32:56 > aaaf25: INFO] D:\local\Temp\jobs\continuous\scripthost\q2ev3aby.2pz>.\bin\Microsoft.Azure.WebJobs.Script.Host.exe
```

Though this error shows up, the script host does show a status of "running."

Thanks,
James

**Comment by mathewc** [comment] 2016-05-02 15:45
Hmmm, that sounds like a Kudu error, and doesn't seem related to this Script library at all. I'll verify by trying the installation steps myself.

**Comment by davidebbo** [comment] 2016-05-02 16:14
Not sure what the issue is, but looking at Option 2 on https://github.com/Azure/azure-webjobs-sdk-script/wiki, I think we should simply retire that option. It only made sense in the early days. The one supported way to run Functions in Azure is via a Function App, which can be upgraded to use private bits using this technique: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension

**Comment by davidebbo** [comment] 2016-05-02 16:15
Closing here, since whatever issue it was is likely Kudu and not Script, and it may no longer be relevant.

**Closed by davidebbo** 2016-05-02 16:15 UTC

**Comment by jamesdixon** [comment] 2016-05-02 16:29
> Hmmm, that sounds like a Kudu error, and doesn't seem related to this Script library at all. I'll verify by trying the installation steps myself.

Thanks, @mathewc. As I mentioned, the error didn't occur until I tried anything greater than v1.0.0-alpha1-10127 -- let me know if you have different results.

> Not sure what the issue is, but looking at Option 2 on https://github.com/Azure/azure-webjobs-sdk-script/wiki, I think we should simply retire that option. It only made sense in the early days. The one supported way to run Functions in Azure is via a Function App, which can be upgraded to use private bits using this technique: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension

@davidebbo, I had also opened #319 yesterday where you described the private extension taking over the web root. If I'm correctly understanding what you said, then I'd have to run the function script host on a different App Service instance than my application, effectively having to provision two instances rather than one. If that is the case, option 2 at least gives me the option to run both my application and the script host on the same instance. Let me know if I'm not understanding this properly.

**Comment by davidebbo** [comment] 2016-05-02 16:34
Correct that is the Functions model. Functions run in their own App and do not coexist with a regular Web App. OTOH, WebJobs (which are still very much supported) do support running in the same app.

WebJobs and Functions have similarities, but they are different offerings with important differences in their runtime model.

**Comment by jamesdixon** [comment] 2016-05-02 16:39
@davidebbo ah, ok, thanks for the explanation. When you had spoken of "Function app," I'd just assumed it was another name for WebJobs. My use case is strictly for being able to trigger WebJobs via QueueTriggers, etc. That said, I'm assuming that in order to use triggered WebJobs within my current application, I _cannot_ use the private site extension?

**Comment by davidebbo** [comment] 2016-05-02 16:42
Correct, for WebJobs, you'd not use a private site extension (unless you use a private Kudu, which is a whole other thing). But why do you even need to use the Script library for this? The base WebJobs SDK directly supports QueueTriggers.

**Comment by mathewc** [comment] 2016-05-02 16:50
If you don't require WebHook/Http support, then the Functions runtime can be run as a regular Continuous WebJob. People might want to do this if for example they want to use Node.js or another non C# language.

**Comment by jamesdixon** [comment] 2016-05-02 16:50
Even for Node WebJobs? I was under the impression that I had to use this project to take to use a QueueTrigger

**Comment by jamesdixon** [comment] 2016-05-02 17:00
@mathewc thanks. I believe that confirms my need for using this project. Appreciate the clarification!

**Comment by davidebbo** [comment] 2016-05-02 17:03
Looking back at the original error, I'm guessing that it may have been a random issue not specifically linked to the script runtime version. Have you just seen this error the one time, or does it consistently go from working to not working as you switch runtime version?

**Comment by jamesdixon** [comment] 2016-05-02 17:04
It's consistent, but more than happy to give it a go again if you'd like.
