### ISSUE TITLE
Continous Deployment with Function App - portal caches old files

### ISSUE THREAD

**Issue by xzuttz** [Azure/azure-webjobs-sdk-script#1527] opened 2017-05-20 20:23 UTC
I've set up Continuous Deployment with an Azure Function and a Github repository. 

There is a guide on how to do that here: 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment

When there is an update to the target branch, Azure catches it and updates the files on the Function Apps FTP server. However, the portal caches the old files, and the old files are the ones that are being executed.

#### Repro steps

1. Create a Function App
2. Create a Time Trigger within the Function App
3. Set up Continuous Deployment with Github and choose a branch
4. Make an update to the branch
5. Verify that the update has been triggered successfully by going to Function App -> Platform Features -> Deployment options. There should be a checkmark indicating the update has been triggered
6. Verify that the latest files are on the FTP server for the Function App
7. Verify that the Azure Portal holds the old files
8. Verify that the old files are the ones being exeucted. This can be seen in the "Montior" section of the Time Trigger

#### Expected behavior

Im expecting the portal to show the latest files and to execute them

#### Actual behavior

Old files are shown and executed

#### Related information 

https://github.com/Azure/azure-webjobs-sdk-script/issues/953

**Comment by xzuttz** [comment] 2017-05-23 06:43
@fabiocav @mathewc did anyone have a look at this?

**Comment by mamaso** [comment] 2017-07-17 18:00
I've followed the repro steps above and am unable to reproduce the behavior, the file watcher picks up the changes and begins executing the new timer trigger.

One point of potential confusion is that the functions portal will not automatically refresh with the new code, that requires a manual refresh.

@xzuttz I'm going to close this out, if you're still running into this issue please reopen and add any extra information.

**Closed by mamaso** 2017-07-17 18:00 UTC

**Comment by keimgf** [comment] 2017-07-17 18:31
@mamaso what do you mean with a manual refresh?

**Comment by mamaso** [comment] 2017-07-17 18:37
![image](https://user-images.githubusercontent.com/9870694/28283920-473a15e0-6ae4-11e7-9cf9-c463814eed9d.png)

Highlighted the refresh button. The portal needs to refresh to hit the function app backend for the updated code files.
