### ISSUE TITLE
Create schema for function.json and host.json

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#878] opened 2016-11-04 18:28 UTC
Will be useful for tooling. I'll need this by 11/11 at the latest. function.json is a higher priority. 

Once we have this done, we'll enable it for IDEs and in the portal. 

Actions:

- [x] Define host.json schema
- [x] Publish host.json schema
- [x] Define function.json core schema
  - [x] HTTP trigger
  - [x] Timer trigger
  - [x] Queue trigger
  - [x] Event Hub trigger
  - [x] Service Bus trigger
  - [x] Blob trigger
  - [x] Manual trigger
  - [x] Storage Table input binding
  - [x] Storage Table output binding
  - nasoni
    - [x] Mobile tables input binding
    - [x] Mobile tables output binding
    - [x] DocumentDB input binding
    - [x] DocumentDB output binding
  - mamaso
    - [x] Notification hubs output binding
    - [x] Twilio SMS output binding
    - [x] SendGrid output binding

- [x] Publish function.json schema

**Comment by fabiocav** [comment] 2016-11-05 00:14
I think your original title was correct. The project.json schema already exists and just needs to be used in the portal/tooling. We need to create the other 2.

**Comment by mathewc** [comment] 2016-11-07 04:36
This is a duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/41 that I created a long time ago

**Comment by fabiocav** [comment] 2016-12-09 20:50
host.json is done and has been published to schema store

**Comment by fabiocav** [comment] 2016-12-13 18:23
Adding the list of actions so we can better track progress:

- [ ] host.json schema
- [ ] function.json core schema
  - [ ] HTTP trigger
  - [ ] Timer trigger
  - [ ] Queue trigger
  - [ ] Event Hub trigger
  - [ ] Service Bus trigger
  - [ ] Blog trigger
  - [ ] Manual trigger
  - [ ] Storage Table input binding
  - [ ] Storage Table output binding
  - [ ] Mobile tables input binding
  - [ ] Mobile tables output binding
  - [ ] DocumentDB input binding
  - [ ] DocumentDB output binding
  - [ ] Notification hubs output binding
  - [ ] Twilio SMS output binding
  - [ ] SendGrid output binding

**Comment by fabiocav** [comment] 2016-12-13 18:25
@lindydonna added a list of actions so we can better track the progress on this.

**Comment by paulbatum** [comment] 2016-12-13 19:02
I'm moving this to Jan milestone to make it easier to track what is outstanding for our last runtime update for the calendar year. We should still prioritize finishing this work given that the bulk of the effort is done.

**Comment by fabiocav** [comment] 2016-12-13 19:43
Adding @mamaso and @soninaren.

I've committed the files with #1046. Will follow up to coordinate updates.

**Comment by fabiocav** [comment] 2016-12-21 02:00
@mamaso now that we have the initial version of the function.json schema done, can you go ahead and open a PR with the appropriate changes?

**Comment by mamaso** [comment] 2017-01-03 16:43
Closing as completed

**Closed by mamaso** 2017-01-03 16:43 UTC
Labels: feature, in progress
