### ISSUE TITLE
CLI: Function compilation error (C#)

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#996] opened 2016-11-28 16:13 UTC
Hi all, 

when I try to run a function (C#) with the azurefunctions CLI via `func run <methodname>` that has a dependency to a third party library (i.e. `ImageResizer`) I get the following error:

```
Reading host configuration file 'C:\Users\olarafat\repos\serverless-imagemanipulation\host.json'
Function compilation error
run.csx(1,7): error CS0246: The type or namespace name 'ImageResizer' could not be found (are you missing a using directive or an assembly reference?)
run.csx(7,24): error CS0103: The name 'ImageResizer' does not exist in the current context
run.csx(12,13): error CS0246: The type or namespace name 'ResizeSettings' could not be found (are you missing a using directive or an assembly reference?)
run.csx(12,52): error CS0103: The name 'FitMode' does not exist in the current context
run.csx(19,13): error CS0246: The type or namespace name 'ResizeSettings' could not be found (are you missing a using directive or an assembly reference?)
run.csx(19,52): error CS0103: The name 'FitMode' does not exist in the current context
```

The NuGet packages haven been restored via `dotnet restore`.
The function works when deployed to Azure.

#### Repro steps

The code and configuration can be found here: [https://github.com/arafato/serverless.imageresizer](https://github.com/arafato/serverless.imageresizer)

#### Expected behavior

A locally running function.

#### Actual behavior

An exception (see above)

**Comment by lindydonna** [comment] 2016-11-29 22:21
@arafato What version of the azure functions CLI are you using?

**Comment by lindydonna** [comment] 2016-11-29 23:11
I can't reproduce. I cloned your repo and ran with the latest version of the Functions CLI (https://www.npmjs.com/package/azure-functions-cli). There is a bug with the CLI where you can't use a directory name with dot "." as it tries to generate an invalid hostname.

You should **not** restore nuget packages with `dotnet restore`. The Functions CLI will restore nuget packages and operates slightly differently.

**Comment by lindydonna** [comment] 2016-11-29 23:16
Btw, make sure you set a value for your connection strings in appsettings.json. For instance:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "connection string value"
  }
}
```

**Comment by arafato** [comment] 2016-11-30 07:50
@lindydonna thanks for your support! 
I'm using the following version:
- Azure Functions Cli (1.0.0-beta.5)
- Function Runtime Version: 1.0.0.0

Adding the `AzureWebJobStorage` fixed it, though.
Is it possible to attach a debugger to a C# function? It works with Node.js. Adding a breakpoint to a `.csx` file does not work. I get the message _Breakpoint ignored because generate code not found (source map problem)?_ 
Any recommendations? Thanks!

**Comment by lindydonna** [comment] 2016-12-16 02:11
@arafato You can't add breakpoints to C# files in VS code, you need to use Visual Studio for that. Please see https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/ for details.

I think the original issue is now resolved, is that correct?

**Comment by lindydonna** [comment] 2016-12-21 22:03
Closing issue, please reopen if the issue persists

**Closed by lindydonna** 2016-12-21 22:03 UTC
Labels: CLI, no-repro, pending-customer-response
