### ISSUE TITLE
Accessing the Location property of the "edge_nativeclr" assembly raises an mscorlib exception "Illegal characters in path" 

### ISSUE THREAD

**Issue by CodeFromGround** [Azure/azure-webjobs-sdk-script#494] opened 2016-07-13 07:42 UTC
When accessing the Location property of the "edge_nativeclr" assembly an mscorlib exception "Illegal characters in path" is raised.

Can be easy reproduced by creating a manual triggered Azure Function like this:

`
	var list = AppDomain.CurrentDomain.GetAssemblies()
	                        .Where(a => a.FullName.StartsWith("edge_nativeclr"))
	                        .Select(a => a.Location).ToList();
`

**Comment by mathewc** [comment] 2016-07-13 15:21
What are you trying to do? Likely this same issue exists outside of this repo, e.g. if you tried the same code from a regular Console app that uses Edge?

**Comment by CodeFromGround** [comment] 2016-07-13 16:57
It's not my code that fails, it's the code of the [RazorEngine](https://github.com/Antaris/RazorEngine). I tried to render html mails in my Azure Function and that failed. Running my code in a "classic" Web Role worked fine so I drilled down the issue to this code. Some assemblies return an empty string or null as result which is pretty fine but raising an "invalid characters in path" exception is pretty nasty because it makes the whole RazorEngine lib not working there.

**Comment by fabiocav** [comment] 2016-07-13 17:18
So to clarify, was the issue you ran into related to something you were trying to do with Edge? Or is your original problem when trying to use RazorEngine? If it was the later, can you share the code that caused the problem with RazorEngine? 
Depending on how assemblies are loaded into the AppDomain, the Location property will indeed be an empty string, that is expected.

**Comment by CodeFromGround** [comment] 2016-07-13 17:37
I setup an Azure Function App with a Blob trigger in order to process mails from a queue. My intention was not to use Edge. I developed the code in VS and copied it afterwards into the Azure Function (C#) were the code raised an exception. I am using the RazorEngine as a Nuget package (latest). So I traced the issue to the [code](https://github.com/Antaris/RazorEngine/blob/fe78af7164dfc9570f5c44a41accc7ffbde26145/src/source/RazorEngine.Core/Compilation/ReferenceResolver/UseCurrentAssembliesReferenceResolver.cs) in the RazorEngine and did a repro with a simple line of code to prove the behavior. In this specific case the assembly throw the exception when accessing it's Location property while others return null or empty (which is pretty fine).

**Comment by CodeFromGround** [comment] 2016-07-13 18:00
Here is the exception info from my repro. Hope that helps.

Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.RuntimeAssembly.get_Location()
   at RazorEngine.Compilation.ReferenceResolver.UseCurrentAssembliesReferenceResolver.<>c.<GetReferences>b__0_0(Assembly a)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at RazorEngine.Compilation.CompilerServiceBase.<GetAllReferences>d__45.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at RazorEngine.Compilation.DirectCompilerServiceBase.Compile(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileTypeImpl(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType_Windows(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(TypeContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at Submission#0.Run(String input, TraceWriter log) in D:\home\site\wwwroot\ManualTriggerCSharp1\run.csx:line 26

**Comment by fabiocav** [comment] 2016-07-13 18:50
The code you've linked to will indeed fail in when/if exceptions are thrown when getting the location value. As @mathewc, this is something you'd able to observe even with a simple console app, and not specific to the Functions runtime. Perhaps opening an issue or submitting a PR against the RazorEngine repo to ensure that code deals with those conditions would be the best course of action.

**Comment by CodeFromGround** [comment] 2016-07-13 18:59
But how should the code deal with it. Building a black list of "bad assemblies" depending on the host system? I think there is no chance that they will accept such a "workaround" as PR. IMHO there should never be an exception (invalid characters in path!) when calling a getter of a property of Assembly.Location. That is not an acceptable behavior from a consumer perspective.

Is there any chance to unload this Assembly from the Azure Function App default app domain or to prevent/block it's loading by the function runtime? Especially when using a C# version.

**Comment by fabiocav** [comment] 2016-07-13 19:18
This is a .NET Framework exception, which in this case, happens to be triggered by the way Edge loads. 

RazorEngine might encounter the same behavior outside of the context of Functions (and Edge), and in the code path you've linked to, they would likely handle it the same way they do for dynamic assemblies and ignore them. This would essentially enhance the logic they already have in place to ignore assemblies they're unable to reference.

Edge is a core Azure Functions dependency, and although we do have plans to provide better isolation between invokers, which would allow us to avoid having that assembly in the AppDomain used for C# functions, this is not something that will happen before GA.

**Comment by fabiocav** [comment] 2016-07-13 22:19
@CodeFromGround closing this as there will be no action at this point, but please let me know if you feel we need to reevaluate.

**Closed by fabiocav** 2016-07-13 22:19 UTC

**Comment by mathewc** [comment] 2016-07-14 03:52
I agree with Fabio. Code that is dynamically loading assemblies from the AppDomain must be robust/defensive enough to handle the different types of assemblies that might be encountered (dynamic assemblies, etc.).

**Comment by CodeFromGround** [comment] 2016-07-14 05:00
The [Microsoft Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229006.aspx) stating that:

> AVOID throwing exceptions from property getters.

> 
Property getters should be simple operations and should not have any preconditions. If a getter can throw an exception, it should probably be redesigned to be a method. Notice that this rule does not apply to indexers, where we do expect exceptions as a result of validating the arguments.

So there is no other chance than to do a try catch around the this getter. Just for asking the Location property value of an assembly. Nothing else! No Type loading etc. Sorry but I can't image that this is intended by design. 
But OK we keep that issue closed. I will skip that Azure Function stuff and try something else...

**Comment by fabiocav** [comment] 2016-07-14 05:50
I'm don't disagree with you. It is unfortunate that the `Assembly` type allows a condition that violates the design guideline you've cited (it's also code that likely predates that guideline). It also, by design, throws `NotSupportedException` if you're dealing with a dynamic assembly, which is something RazorEngine already deals with in order to prevent issues.

Unfortunately, the Assembly type behavior is not something we can fix within this repo, and the workaround is not feasible at this point.

As I mentioned, this is a relatively simple fix to put in place for RazorEngine, and since it is something that would improve the reliability of their project, I would imagine they would appreciate that contribution.

Keep in mind that another option you could explore is to execute the code that consumes RazorEngine in a different AppDomain. That would give you full control over what assemblies are ultimately loaded there, so that is another workaround that may yield better performance (since you won't add a reference to every assembly loaded in the host's AppDomain) and potentially better behavior with their framework, as they describe [here
](https://github.com/Antaris/RazorEngine#temporary-files)

I'm sorry if this steers you away from Azure Functions. We try to go the extra mile to address customer concerns and provide the best possible experience, but this issue is unfortunately not something that can be addressed with a reasonable amount of effort.

**Comment by CodeFromGround** [comment] 2016-07-14 15:00
Fabio I would like to thank you for helping me with my issue. I truly understand that this is not a problem that resides in this repo, it's further more a general problem. I will try to test a solution working with a separate AppDomain and check whether this is working for us or not. Beside that I would be happy if there is an option in the future to decide which assemblies are pre-loaded in the default app domain of an C# Azure Function. :-)
