### ISSUE TITLE
Relative path for scriptFile

### ISSUE THREAD

**Issue by bondz** [Azure/azure-webjobs-sdk-script#1229] opened 2017-02-23 13:13 UTC
I'm trying to setup a bot function using typescript, my app is compiled in a `build` folder which contains an `index.js`, I've tried to set the path in `function.json` in the root directory using relative and absolute paths. but the app won't boot unless the file is in the same location as `function.json`

```json
{
  "disabled": false,
  "scriptFile": "./build/index.js",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```
My folder structure is 
```text
|   .gitignore
|   host.json
|   
+---messages
|   |   function.json
|   |   package.json
|   |   test.js
|   |   
|   +---.vscode
|   |       launch.json
|   |       
|   \---build
|           index.js
|           
\---PostDeployScripts
        runGulp.cmd
```

I've tried `build/index.js`, `D://site.../build/index.js`

**Comment by bondz** [comment] 2017-02-23 13:23
Just checking now, and it looks like #1132 solves this. Not sure if its published yet though.

**Comment by mathewc** [comment] 2017-02-23 17:49
Right - that release is rolling out now. The issue is likely that you don't have it yet. ETA is today for the release to complete.

**Comment by bondz** [comment] 2017-02-23 17:59
OK, thanks. I'll check again in a few hours.

**Comment by lindydonna** [comment] 2017-02-23 23:32
Closing this as the release should fix your issue. If you want to manually use the later version, set `FUNCTIONS_EXTENSION_VERSION` to 1.0.10757

**Closed by lindydonna** 2017-02-23 23:32 UTC

**Comment by bondz** [comment] 2017-02-24 02:20
👍 It works, although, `https://{BotID}.scm.azurewebsites.net/api/functions` stops showing anything when a relative path is used.

**Comment by lindydonna** [comment] 2017-02-24 02:21
Yes, we have a bug to track this: https://github.com/projectkudu/kudu/issues/2334

**Comment by lindydonna** [comment] 2017-02-24 02:27
@bondz We actually had to roll back part of the latest release, so the scriptFile update will stop working once your site restarts (this is why we didn't advertise the feature widely). You can manually pin to a pre-release version by setting the app setting `FUNCTIONS_EXTENSION_VERSION` to `1.0.10765`.

**Comment by bondz** [comment] 2017-02-24 02:31
@lindydonna thanks, done that.
