### ISSUE TITLE
Blob trigger gets invoked on multiple hosts listening on a storage account

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-webjobs-sdk-script#1052] opened 2016-12-14 23:15 UTC
I deployed my local changes with the new VS Functions tooling ,and when developing locally both the local func.exe host and function app host triggered for every blob uploaded. This was unexpected because the mental model is one execution per trigger,  and number of hosts isn't in the picture.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A : Create a blob triggered function using a VS tooling, and deploy it to a function App. Make sure to use the same storage account information in both places

2. Step B : Upload a blob in the location to trigger the function

#### Expected behavior

Only one instance should pick up the blob input and execute. Or better yet should be configurable on whether a particular host should pick it up or all or any one.

#### Actual behavior

All hosts/instance pick up the trigger

#### Known workarounds

No known workarounds except for running a single host

#### Related information 

I couldn't find it , but if there isn't then documentation around this behavior would be helpful.

* Programming language used : C#
* Links to source : internal

**Comment by lindydonna** [comment] 2016-12-15 01:19
Afaik this is by design. @mathewc can you confirm?

This is indeed different than how the other triggers work--blob triggers are special. I suggest we document this--I also found it surprising at first.

**Comment by mathewc** [comment] 2016-12-15 16:34
Here's what I think is happening. The singleton mechanism used under the covers to ensure only one host processes a blob is based on the HostId. In regular scale out scenarios, the HostId is the same for all instances, so they collaborate via blob leases behind the scenes using the same lock blob scoped to the host id.

Likely for local the same host ID of the remote Function App isn't being used, so they are viewed as two different hosts. Normally only 1 of N host instances is scanning for new blobs (based on a singleton host id lock). When it finds a new blob it adds a queue message for it and one of the N hosts processes it. In your case because of the different host ids, you have 2 hosts scanning for blobs, so 2 queue messages, and the blob gets processed twice.

@brettsam can confirm.

**Comment by brettsam** [comment] 2016-12-15 17:06
@fashaikh -- are you using different `AzureWebJobsStorage` storage accounts for the local and cloud versions? Note that this is (possibly) different than the storage account that the Blob trigger is using.

**Comment by fashaikh** [comment] 2016-12-15 20:05
No its the same storage account, both locally and on the cloud. 
The blob trigger also uses the same storage account on both hosts as `AzureWebJobsStorage`

**Comment by brettsam** [comment] 2016-12-15 22:35
What @mathewc said looks to be correct. When you run locally, it looks like you are assigned a HostId like `{MachineName}-{AppName}` yet when you run in the cloud, we generate your HostId based on your site name here: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/App_Start/WebHostResolver.cs#L165-L178.

That effectively means you're running two different hosts that are both watching the same blob path. So, by design (from that standpoint), it's working as expected.

If you want your local host to be treated like another instance of your cloud host, you should be able to set the 'id' property in your host.json file to match your site name. I did a really brief test and that seemed to work for me.

**Comment by brettsam** [comment] 2016-12-15 22:42
@lindydonna -- there's likely going to be some confusion here with people that use the same storage account for everything locally and in the cloud. It gets especially confusing when some things match and others don't. Do we give guidance anywhere on how you should be setting this up?

**Comment by lindydonna** [comment] 2016-12-16 00:10
@brettsam Your understanding of the HostID generation is correct (and it leads to some bugs, such as the AppName folder having invalid characters for a host name https://github.com/Azure/azure-webjobs-sdk-script/issues/1006). There's also currently a bug where the host.json file was **not** picking up ID from host.json at least in my repro: https://github.com/Azure/azure-webjobs-sdk-script/issues/1007. 

I agree that this is very confusing. We don't yet have any documentation on how to do local CLI setup but I got this same exact feedback from Fabio today so I'll add a wiki page soon. :)

What other trigger types have this kind of dependency on host ID?  Do we have documentation anywhere?

**Comment by lindydonna** [comment] 2016-12-16 01:54
@fashaikh If we documented the behavior of the CLI for this trigger and others, would that resolve your issue?

**Comment by brettsam** [comment] 2016-12-16 14:48
@lindydonna  -- Technically they all operate like separate hosts in this case, but blobs are a little different from some of the other triggers because they don't delete the blob once they process it. That allows other hosts to process it on their own. Some examples of what would happen if you ran the same app in two machines with different hostIds (just off the top of my head):
- Timer: You'd get the timer firing on both hosts. 
- Queues: It'd be a race to see who could dequeue the item first and only that host would run the function. This may actually be closer to what Faiz expected, and makes it even move confusing when blobs and timers behave differently.
- SB: Same as queues -- one host would get the messages and the other would never see them.

It seems like you'd want two 'modes' for local development:
1. The HostId and all of the storage connection strings **match** both locally and in the cloud. This would make this running instance just like one of the ones running on an Antares machine.
2. The HostId and all of the storage connection strings are **different** locally and in the cloud. This would make the local host completely independent of the others.

Any mixing of those leads to the oddities that Faiz is seeing here.

**Comment by lindydonna** [comment] 2016-12-19 19:33
Closing this issue and tracking the work here: https://github.com/Azure/Azure-Functions/issues/112

**Closed by lindydonna** 2016-12-19 19:33 UTC
Labels: docs
