### ISSUE TITLE
Better support for InOut bindings in scripts

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#107] opened 2016-03-16 11:37 UTC
If you create an InOut binding, one IValueBinder is used for the In and one is used for the Out. Several of our Bindings rely on this being the same binder (there's some stored state). You can get to it from private reflection but we should look into a better solution.

**Comment by fabiocav** [comment] 2016-03-16 14:04
Related to #89

**Comment by mathewc** [comment] 2016-03-22 16:15
I beleive this is a dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/49.

**Closed by mathewc** 2016-03-22 16:15 UTC

**Comment by brettsam** [comment] 2016-03-22 16:17
Yup, looks the same.
