### ISSUE TITLE
IJobActivator for dependency injection

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-webjobs-sdk-script#2133] opened 2017-11-15 03:39 UTC
Hi, Team.

I know the `IJobActivator` interface for Azure WebJob enables us to handle dependencies quite easily and, with this, we don't have to run static entry points any longer.

I wonder if you have ever considered to implement this `IJobActivator` so that we can handle dependencies with more convenience or not?

Cheers,

**Comment by christopheranderson** [comment] 2017-11-22 19:31
This is a dupe of this issue: https://github.com/Azure/azure-webjobs-sdk/issues/1206

This is something we'll be trying to add to Functions 2.0 (WebJobs 3.0). Please +1 that linked issue to show your support.

**Closed by christopheranderson** 2017-11-22 19:31 UTC
