### ISSUE TITLE
Why do I see "Never Finished" for Azure Functions? Are they unreliable for production?

### ISSUE THREAD

**Issue by BitProgress** [Azure/azure-webjobs-sdk-script#2187] opened 2017-12-04 21:32 UTC
I often see "Never Finished" for my Azure Functions, which concerns me. The functions listens for events from event queues, and the received information is VERY important. The event queue buffers data from an IoT Hub.

_context: 683a9724-9452-4024-b593-2bfa608d4530
_context: a327954c-e58a-45ce-b318-2c587b735012

How can I find out what is happening?

- Timestamp: Between 12/4/2017 5:33:14 PM and 12/4/2017 7:20:02 PM
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: XXX
- Function name(s) (as appropriate): HandleIoTHubMessages
- Invocation ID: 683a9724-9452-4024-b593-2bfa608d4530 / a327954c-e58a-45ce-b318-2c587b735012
- Region: West Europe

I have 2 different functions apps running, and I see issues on both!
And it is a problem, that the event is never handled.
When I read about the event queue, the azure function should retry handling that specific event, and never move on.

**Comment by jeffhollan** [comment] 2017-12-07 00:33
Few points things here that may help.  First there are some hiccups with the monitoring pane in that it is really only intended for simple debugging and testing.  We have a work item I believe @alexkarcher-msft is opening in the azure-functions-ux repo to add a warning here.  We recommend using App Insights for more reliable and production-grade monitoring and will be doing work over next few months to improve that integration into this pane.  In short - there is a very good chance these runs actually executed and completed successfully, but for one reason or another aren't showing status right here.  Let me know if you have any other data to know if these may in fact have missed.

The other point worth noting is the behavior of the Event Hub trigger.  For queues there is a concept of retrying the request on a failure, but for event hub there is a sequence number that we increment after a function completes execution (successfully or with exceptions).  In that way you have at least once guaranteed execution, but no retries (can't process the next message in partition until sequence advances so a single bad message could halt the line).  If you want retries you may need to use a queue.  The other pattern recommended with messaging services like Event Hubs is to `catch` any exceptions in the function code, you can then add the message into your own "dead-letter" queue or potentially into a "exceptions" message stream to handle later.  But Event Hubs itself doesn't provide any retry mechanisms as that type of transactionality is reserved for message brokers like queues and topics.

Feel free to close the issue if that resolves - or let me know if I may have missed anything.

**Comment by dewanymca** [comment] 2017-12-31 17:00
Jeff- I have been experiencing same issue with sB topic bindings, where in under load test message are getting processed successfully but log shows "never finished'(orange status) . And because of this issue Subscription message are available again for function to pick and resulting in duplicate. i have my custom telemetry and other ways to know whether message has been processed. With a simple load test of 2 minute, i am able to reproduce the issue. Let me know if you want to see the repro.

**Comment by jeffhollan** [comment] 2018-01-23 01:00
Thanks closing this issue and responded to related issue

**Closed by jeffhollan** 2018-01-23 01:00 UTC
Labels: pending-customer-response
