### ISSUE TITLE
Provider model for Binding/Extension Integration

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#250] opened 2016-04-12 18:26 UTC
Some refactoring / cleanup that is somewhat related to https://github.com/Azure/azure-webjobs-sdk-script/issues/168. These are just some incremental improvements moving us in that direction.
- Move all extension specific stuff out of FunctionBinding class - all description for each binding type should be centralized in binding specific types. Perhaps a provider model for these bindings and metadata types
- Similarly, move the extension specific trigger parsing logic out of FunctionDescriptorProvider and into the above mentioned provider model. Basically we want it to be possible to implement a simple provider per extension that allows it to serve up all the runtime needs
- Move all BindingMetadata parsing out of ScriptHost and into provider.
- Move all our built in extensions onto this provider model

**Comment by CrazyTuna** [comment] 2016-04-21 20:45
Matthew, does that mean that we will be able to plug our own binding extensions as describe [here](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Binding-Extensions-Overview) ?

**Comment by mathewc** [comment] 2016-04-21 21:12
Yes. The intent is to make it easy for extension authors who have written WebJobs SDK extensions to have them "just work" in Azure Functions. Thus far, we have had to onboard each extension manually. We want to have a "pluggable" model where the extension author provides some more metadata/info, and we're able to make it work with Functions.

**Comment by christopheranderson** [comment] 2016-06-21 18:32
RC Justification: language/binding extensibility

**Comment by MikeStall** [comment] 2017-06-27 20:26
This is related to https://github.com/Azure/azure-webjobs-sdk-script/issues/1406 .

**Comment by lindydonna** [comment] 2017-07-10 22:17
Duplicate of #1406

**Closed by lindydonna** 2017-07-10 22:17 UTC
Labels: duplicate, engineering, feature:byob
