### ISSUE TITLE
Investigate eventsource performance for high-throughput scenarios

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1427] opened 2017-04-16 18:32 UTC
Determine whether moving from the `WriteEvent(int eventId, params object[] args)` overload is worthwhile

See: https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource.writeeventcore(v=vs.110).aspx

**Comment by paulbatum** [comment] 2017-04-18 20:52
Dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/1362

**Closed by paulbatum** 2017-04-18 20:52 UTC
