### ISSUE TITLE
Timer tigger fails to fire 

### ISSUE THREAD

**Issue by LoungeFlyZ** [Azure/azure-webjobs-sdk-script#336] opened 2016-05-05 15:25 UTC
I have a C# function triggered every 30 mins.  However from time to time it stops firing.  When that happens I log into the Azure portal, go open that function and magically it springs back to life and the trigger fires again.  Its like its being woken up when I go in there.  

I sadly have no solid repro i'm sorry.

**Comment by davidebbo** [comment] 2016-05-05 15:56
Is your function running in a Dynamic plan or Classic plan? If classic, make sure it is Basic or Standard, and has Always On turned on.

Also, can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

One more thing: the approximate time where you saw this happen could help track it down.

**Comment by LoungeFlyZ** [comment] 2016-05-05 16:01
We have it in an S1 plan.  Not sure how to tell if Classic or Dynamic?  Must be dynamic as we don't have the Always On toggle.

**Comment by davidebbo** [comment] 2016-05-05 16:04
S1 is actually Classic. To check the Always On toggle:

- Functions app settings / Go to App Service Settings
- Settings / Application Settings
- Look for Always On

**Comment by LoungeFlyZ** [comment] 2016-05-05 16:32
Ah right! Thanks!  Probably would be useful for that to be on by default no?

**Comment by davidebbo** [comment] 2016-05-05 16:33
Yes, it really should be. You created the Function App using the Azure Portal, right?

**Comment by davidebbo** [comment] 2016-05-05 16:39
I confirmed that creating a new S1 Function app does *not* auto set the Always On bit. Definitely a bug which we'll fix. I'll close this issue since that logic lives in the Azure portal which is not on GitHub.

Thanks for reporting!

**Closed by davidebbo** 2016-05-05 16:39 UTC

**Comment by LoungeFlyZ** [comment] 2016-05-05 16:40
Thanks for the assistance! Yep, created via portal.
