### ISSUE TITLE
Script error - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1568] opened 2017-06-05 08:43 UTC
Hi,

I have a function, which performs following tasks:

1. fetches data from a queue
2. deserializes it and pushes to a storage table
3. pushes raw data to another storage table

`function.json` file looks like following:

```
{
  "scriptFile": "MyFunction.dll",
  "entryPoint": "MyFunction.Run",
  "disabled": false,
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "eventAggregator",
      "connection": "StorageConnectionString"
    },
    {
      "tableName": "deviceEvent",
      "connection": "StorageConnectionString",
      "name": "deviceEventTable",
      "type": "table",
      "direction": "out"
    },
    {
      "tableName": "eventLog",
      "connection": "StorageConnectionString",
      "name": "eventLogTable",
      "type": "table",
      "direction": "out"
    }
  ]
}
```

and this function code:

```
public class DeviceEventProcessor
    {
        private static CloudTable _deviceEventTable;
        private static ICollector<EventLog> _eventLogTable;
        private static TraceWriter _log;

        public static void Run(string myQueueItem,
            CloudTable deviceEventTable,
            ICollector<EventLog> eventLogTable,
            TraceWriter log)
        {
            _log = log;
            _deviceEventTable = deviceEventTable;
            _eventLogTable = eventLogTable;

            _log.Trace(new TraceEvent(TraceLevel.Info, $"Processing {myQueueItem} item."));
            EventAppeared(myQueueItem);
        }

        private static void EventAppeared(string @event)
        {
            _log.Trace(new TraceEvent(TraceLevel.Info, "Deserializing entity..."));

            var data = JsonConvert.DeserializeObject<DeviceEvent>(@event);
            var pk = $"{ClearLocationName(data.Name)}_{data.Sn}";
            data.PartitionKey = pk;
            data.RowKey = $"{DateTime.MaxValue.Ticks - DateTime.Parse(data.Date).Ticks:D19}";

            // Table Storage doesn't support int[] so we have to convert
            // values to one of supported types
            data.DetailedValues = string.Join("|", data.Values); 

            _log.Trace(new TraceEvent(TraceLevel.Info, $"Adding entity with PK {data.PartitionKey} and RK {data.RowKey} with values {data.Values}"));
            var operation = TableOperation.InsertOrReplace(data);
            _deviceEventTable.Execute(operation);

            _log.Trace(new TraceEvent(TraceLevel.Info, "Inserting event log"));
            _eventLogTable.Add(new EventLog
            {
                Event = @event,
                PartitionKey = pk,
                RowKey = DateTime.Now.Ticks.ToString()
            });

            _log.Trace(new TraceEvent(TraceLevel.Info, "Event added"));
        }

        internal static string ClearLocationName(string name)
        {
            var disallowedChars = new[]
            {
                '#', '!', '@', '`', '~', '$', '%', '^', '&', '*', '(', ')', '+', '=', '{', '}', '[', ']', ':', ';',
                '\'', '"', '<', '>', ',', '.', '?', '/', '|', '\\'
            };

            if (name.IndexOfAny(disallowedChars) == -1) return name;

            return disallowedChars.Aggregate(name, (input, @char) => input.Replace(@char.ToString(), string.Empty)) + "_2";
        }
    }
```

Now where the problem is - I have Application Insights integrated with this function. Each call generates following 

> error:A ScriptHost error has occurredError while handling parameter eventLogTable after function returned:Collection was modified; enumeration operation may not execute.

with the following trace:

> Microsoft.Azure.WebJobs.Host.FunctionInvocationException
[no stack frames available]
System.InvalidOperationException
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__22.MoveNext
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__20.MoveNext
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__14.MoveNext
Inner exception System.InvalidOperationException handled at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+d__22.MoveNext
System.ThrowHelper.ThrowInvalidOperationException
System.Collections.Generic.Dictionary`2+Enumerator.MoveNext
Microsoft.Azure.WebJobs.Host.Tables.TableEntityWriter`1+<FlushAsync>d__11.MoveNext
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
Microsoft.Azure.WebJobs.Host.Bindings.AsyncCollectorValueProvider`2+<SetValueAsync>d__9.MoveNext
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d

 I tried to create a repro, but it didn't work - I guess it's because I created not enough traffic. What is more - I see this exception in Application Insights but function is executed successfully and all rows are inserted into Table Storage.

**Comment by paulbatum** [comment] 2017-06-05 17:56
So this looks like a hard to repro race condition

**Comment by paulbatum** [comment] 2017-06-05 17:58
The problem is that you've got static variables that you are assigning to within the body of your function. These will get overwritten by subsequent function executions. Instead of using static variables, pass all the state through arguments to your helper functions.

**Closed by paulbatum** 2017-06-05 17:58 UTC

**Comment by kamil-mrzyglod** [comment] 2017-06-05 18:21
@paulbatum Gosh, now when you pointed this out it makes perfect sense. Thank you for help!
