### ISSUE TITLE
CLI: Copy/paste from npm website does not work

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#844] opened 2016-10-28 10:40 UTC
#### Repro steps

Windows 10
Microsoft Edge 38.14393.0.0
Command prompt
npm 3.10.8
1. Copy "npm i -g azure-functions-cli" from [npm website](https://www.npmjs.com/package/azure-functions-cli)
2. Paste to Windows command prompt
#### Expected behavior

npm should install azure-functions-cli.
#### Actual behavior

Wrong npm command syntax:
![functions-error3](https://cloud.githubusercontent.com/assets/23002661/19803895/79a1091e-9d0b-11e6-91fb-72e046234ae2.png)
#### Known workarounds

Type it directly instead of copy/paste.
#### Related information

Seems to be an issue with a wrong charset.

**Comment by lindydonna** [comment] 2016-11-01 18:27
Current branch is CLI2

**Comment by lindydonna** [comment] 2016-11-12 01:26
I can't reproduce. Could it be an encoding issue?

**Comment by mikezks** [comment] 2016-11-17 09:27
Yes, as mentioned above ("Seems to be an issue with a wrong charset.") I am quite sure it is related to encoding.

Therefore it has nothing to do with the CLI itself, but with the npm website. Nevertheless this may lead to confusion for users of the CLI.

Additional info:
Copy/paste of the command in the main content area still fails and is reproducible for me.
Copy/paste of the almost same command form the right area works as intended.

**Comment by lindydonna** [comment] 2016-12-21 21:50
Closing since we can't reproduce :(

**Closed by lindydonna** 2016-12-21 21:50 UTC
Labels: CLI, no-repro
