### ISSUE TITLE
Support API to return runtime version

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#405] opened 2016-05-27 14:13 UTC
Could be part of existing host status API.

**Comment by mathewc** [comment] 2016-05-27 15:19
Closing as dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/403 which I opened yesterday :)

**Closed by mathewc** 2016-05-27 15:19 UTC

**Comment by davidebbo** [comment] 2016-05-27 17:47
Ah, sorry, missed it!
