### ISSUE TITLE
CLI host: Improve host error message when AzureWebJobsStorage connection string is not set

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#972] opened 2016-11-22 22:13 UTC
#### Repro steps

1. Create a new Function app and Function using the CLI. Use a trigger other than HTTP
2. Don't set a value for the AzureWebJobsStorage connection string.
3. Run the Function host (via `func host start`)

#### Expected behavior

Error message saying that the environment variable `AzureWebJobStorage` doesn't exist and is needed for triggers other than HTTP.

#### Actual behavior

```The following 1 functions are in error:
ImageResize: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ImageResize'. Microsoft.Azure.WebJobs.Host: Value cannot be null.
Parameter name: hostAccount.
```

**Comment by paulbatum** [comment] 2016-11-28 19:18
@soninaren Can you take a look at this? I suspect that its a core SDK issue and not a script issue. If so can you file an issue against the SDK and then investigate? We probably just need a better error message.

**Comment by soninaren** [comment] 2016-12-01 00:12
With the code in the current dev branch the actual error is
`Object reference not set to an instance of an object`

It is caused because account is accessed here which is actually null.
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Storage/IStorageAccountExtensions.cs#L14

The cause of the original error was because of ArgumentNullException here.
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerBinding.cs#L70

There is a bug tracking this issue as well. Closing this one and using the core Sdk bug for tracking
https://github.com/Azure/azure-webjobs-sdk/issues/927

**Closed** 2016-12-13 19:22 UTC
