### ISSUE TITLE
Timer trigger schedule won't update

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-webjobs-sdk-script#323] opened 2016-05-02 14:02 UTC
I have a PowerShell script Function that simply runs an executable on a schedule. Currently, the script is set to run every minute as follows in `function.json`:

```
"schedule": "0 * * * * *"
```

However, when I update this property to run the Function every second (`"schedule": "* * * * * *"`), it continues to run the function every minute and not actually update the schedule.

I think this could be related to #213 since I also noticed that when making changes to my PowerShell script Function itself that they don't get registered until after I restart the Function App.

**Comment by davidebbo** [comment] 2016-05-03 23:23
Can you share some more specific repro steps? What I tried:

- New PowerShell timer function
- Verify that it runs every minutes
- Go to integrate tab and change cron to every second
- Back to Develop tab, I see it correctly running every second

Anything different in what you are doing?

**Comment by anweiss** [comment] 2016-05-04 14:20
hey @davidebbo ... in my case, I am setting my app up for CI... so my specific repro steps are as follows:

1. New PowerShell timer function
2. Verify that it runs every x minutes
3. Navigate to Function app settings
4. Click **Configure Continuous Integration** and setup for local Git repository
5. Navigate back to the Develop tab and note that Function has stopped running

If I clone the Git repo, update my timer via `function.json`, commit the change, and push it, the function begins to execute. However, if I update the timer again, commit and push the change, it doesn't change the timer's schedule.

So not sure what's going on in this case.

**Comment by davidebbo** [comment] 2016-05-04 14:28
Ok, so reading these new steps, it sounds like the issue is in fact not about "Timer trigger schedule won't update", but more about "Enabling CI stops the timer function from executing". Correct?

**Comment by anweiss** [comment] 2016-05-04 14:38
that's correct...and that subsequent changes to the timer via Git commits do not get applied

**Comment by davidebbo** [comment] 2016-05-04 23:25
I just tried and still wasn't able to repro. After enabling Local Git and coming back, my new PowerShell timer function is still running every minute.

Does this happen consistently for you, or does it seem random?

**Comment by anweiss** [comment] 2016-05-04 23:52
hey @davidebbo ...so it definitely seems random as I can't reproduce it consistently... did you try updating your timer schedule in `function.json` and then committing/pushing your change to see if the new schedule took effect?

**Comment by mathewc** [comment] 2016-09-19 21:45
Guys, any traction on this issue? Otherwise we should close this out.

**Closed** 2016-10-12 01:00 UTC
Labels: bug
