### ISSUE TITLE
OverflowException in MetricsEventManager

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#2016] opened 2017-10-11 13:24 UTC
Reported by a customer. I see ~1k instances of this error with this stack over the last 7d, affecting 64 individual apps. It likely happens when we aggregate and convert everything to a UInt64. Could we be getting a negative number in there? My initial guess would be `ExecutionTimeInMS` since that's a Sum operation while the rest are Count.

https://github.com/Azure/azure-webjobs-sdk-script/blob/d4acb33b439e75e49cbd96a4c81b2126045d389b/src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs#L488

Stack is:

```
System.OverflowException : Value was either too large or too small for a UInt64.
   at System.Decimal.ToUInt64(Decimal d)
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionActivityTracker.<>c.<RaiseMetricsPerFunctionEvent>b__23_1(IGrouping`2 functionGroups) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\MetricsEventManager.cs : 482
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionActivityTracker.RaiseMetricsPerFunctionEvent() at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\MetricsEventManager.cs : 491
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.MetricsEventManager.FunctionCompleted(FunctionStartedEvent completedEvent) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\MetricsEventManager.cs : 163
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.WebHostMetricsLogger.EndEvent(MetricEvent metricEvent) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\WebHostMetricsLogger.cs : 56
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInstanceMonitor.End(Boolean success) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 267
   at async Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync(FunctionInstanceLogEntry item,CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\FunctionInstanceLogger.cs : 67
   at async Microsoft.Azure.WebJobs.Host.Executors.CompositeFunctionEventCollector.AddAsync(FunctionInstanceLogEntry item,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync[TTriggerValue](TriggeredFunctionData input,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobQueueTriggerExecutor.ExecuteAsync(IStorageQueueMessage value,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ProcessMessageAsync(IStorageQueueMessage message,TimeSpan visibilityTimeout,CancellationToken cancellationToken)
```

**Comment by brettsam** [comment] 2017-10-11 13:33
@mathewc -- any ideas on this one?

**Comment by paulbatum** [comment] 2017-10-25 18:54
dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/1376

**Closed by paulbatum** 2017-10-25 18:54 UTC
