### ISSUE TITLE
Functions based on .net core fails with Microsoft.NET.Sdk.Functions 1.0.7

### ISSUE THREAD

**Issue by borlip** [Azure/azure-webjobs-sdk-script#2224] opened 2017-12-14 00:20 UTC
Create a new Azure Functions project in VS 2017 (version 15.5.1)
By default, it creates dependency on Microsoft.NET.Sdk.Functions 1.0.6
Everything works fine, ie compiles and runs.
After upgrading the above dependency to 1.0.7 it fails after launch on localhost with:
[14/12/2017 12:18:30 AM] ScriptHost initialization failed
[14/12/2017 12:18:30 AM] System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Listening on http://localhost:7071/

The actual function created by a template:
public static class Function1
    {
        [FunctionName("Function1")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]HttpRequest req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = new StreamReader(req.Body).ReadToEnd();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }

**Comment by dersia** [comment] 2017-12-14 01:03
This is a duplicate of https://github.com/Azure/Azure-Functions/issues/625#issuecomment-351563570

**Comment by christopheranderson** [comment] 2018-01-16 18:55
Closed as dupe

**Closed by christopheranderson** 2018-01-16 18:55 UTC
