### ISSUE TITLE
Invalid Bindings are silently ignored

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1509] opened 2017-05-12 23:51 UTC
@davidebbo noticed this. In the below example, a binding of type 'invalid' is declared. This binding is skipped with no error log, and the function runs successfully. The logic that does this is here: https://github.com/Azure/azure-webjobs-sdk-script/blob/3b3e8cb8312060a475d4eb0418fafb4d80f12326/src/WebJobs.Script/Binding/FunctionBinding.cs#L46.

We likely can't change to errors at this point, but we can emit warning logs so people know something is wrong. We should make this error easily searchable in logs so we can scan for it.

```javascript
{
    "bindings": [
        {
            "type": "timerTrigger",
            "name": "timerInfo",
            "direction": "in",
            "schedule": "0 * * * * *"
        },
        {
            "type": "invalid",
            "name": "outBlob",
            "direction": "out",
            "path": "samples-output/test"
        }
    ]
}
```

**Comment by davidebbo** [comment] 2017-05-13 00:01
Yep, a warning would be great, thanks!

**Comment by fabiocav** [comment] 2017-05-15 17:29
This is a duplicate of #1503 , correct?

**Comment by davidebbo** [comment] 2017-05-15 18:16
Right, we both ended up opening it.

**Closed by davidebbo** 2017-05-15 18:16 UTC
