### ISSUE TITLE
Documentation on node.js functions

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1131] opened 2017-01-18 18:19 UTC
_From @cesarvarela on January 14, 2017 3:12_

Can't find where is the convention for how node.js based functions should be defined. Does the main entry point must be called `index.js`? does it have to be specified in the `package.json`'s `main` entry? Is it possible to rename it or place it in another folder?

_Copied from original issue: projectkudu/AzureFunctionsPortal#868_

**Comment by paulbatum** [comment] 2017-01-18 18:19
_From @cesarvarela on January 14, 2017 3:13_

Especificilly I'm interested in bots as a service functions.

**Comment by paulbatum** [comment] 2017-01-18 18:19
@mamaso Can you answer this one?

**Comment by mamaso** [comment] 2017-01-18 19:19
@cesarvarela You can define the main entry point via a `scriptFile` property in function.json: 
`{ scriptFile: 'src/test.js', bindings: ... }`

I like the idea to use the `main` entry point from package.json, that's less functions-specific magic.

**Comment by cesarvarela** [comment] 2017-01-18 19:30
Thanks! Is that documented somewhere? I guess the `scripts` entries are ignored too right (postInstall, preinstall, etc..)?

Regarding the functions-specific-magic, yes please! I think any node developer would expect that node.js functions somehow adhere to the `package.json` conventions.

**Comment by mamaso** [comment] 2017-01-18 19:32
At the moment, we don't run npm install on deployments of / changes to function code.  If you run npm install from dev console (function app settings -> dev console -> cd 'functionname' -> npm install) you should see that your preinstall / postinstall scripts execute

**Comment by cesarvarela** [comment] 2017-01-18 19:40
I would expect `npm install` to be ran too. Specifically because we use TypeScript and use post install to transpile.

Any suggestion on how can we manage that? (other than just pushing the transpiled js)

**Comment by mamaso** [comment] 2017-01-18 19:46
Yep I agree, supporting `npm install` automatically for functions is on the backlog.

You could add a [custom deployment script](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script) to the root of your function app which runs `npm install` for each of your functions

**Comment by cesarvarela** [comment] 2017-01-19 04:05
Looks like the `scriptFile` setting is being ignored, you can try it by just moving the `index.js` file of the basic bot template to a folder and updating the `function.json` accordingly.

`messages: Unable to determine the primary function script. Try renaming your entry point script to 'run' (or 'index' in the case of Node), or alternatively you can specify the name of the entry point script explicitly by adding a 'scriptFile' property to your function metadata.
`

**Comment by fabiocav** [comment] 2017-01-19 04:29
How timely :)

PR #1132 is just out (wrapping up a couple of remaining items) dealing with that exact issue. The problem is with script files outside of the function folder. Different file names work as expected.

**Comment by christopheranderson** [comment] 2017-01-20 18:53
If there are still doc issues, we should open in azure/azure-functions.

**Comment by mamaso** [comment] 2017-01-23 21:08
Closing this out, the only actionable piece here is adding package.json `main` to serve as a `scriptFile` default, but I think that would be better addressed in #73 if we implement it

**Closed by mamaso** 2017-01-23 21:08 UTC
