### ISSUE TITLE
Cannot override azure functions home page

### ISSUE THREAD

**Issue by cloudkite** [Azure/azure-webjobs-sdk-script#986] opened 2016-11-24 22:01 UTC
#### Repro steps

host.json

```
{
  "id": "blahblah234",
  "watchDirectories": [ "Shared" ],
  "http": {
    "routePrefix": ""
  },
  "tracing": {
    "fileLoggingMode": "always"
  }
}
```

function.json

```
{
  "entryPoint": "handler",
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [ "get" ],
      "route": "{page?}",
      "authLevel": "anonymous"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ],
  "disabled": false
}
```

index.js

```
export function handler(ctx, req) {
  return {
    body: '<!doctype html><html><body>hello world</body></html>',
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'max-age=0,no-cache,no-store',
    },
  }
}
```

#### Expected behavior

since`"routePrefix": ""` is empty in `host.json` and "route": "{page?}" is optional. Should I not be able to get to this handler when pathname is `'/'`

#### Actual behavior

shows azure marketing page `Your Function App is up and running`

I am making a single page app and not being able to take over the root url is a major issue for me.

**Comment by fabiocav** [comment] 2016-11-24 22:16
@cloudkite, currently this is not supported. We have an issue requesting this feature (#848) we'll be using that to track any future progress and would be good to thumbs up that as well.

Referencing and closing as duplicate of #848

**Closed by fabiocav** 2016-11-24 22:16 UTC
