### ISSUE TITLE
Third party assemblies do not load every time after idling

### ISSUE THREAD

**Issue by EmilBechMadsen** [Azure/azure-webjobs-sdk-script#1338] opened 2017-03-22 13:40 UTC
I'm experiencing an issue with a blobtriggered function, in which I utilize multiple third party dlls. After running succesfully for a while, it will fail to load the assemblies in the bin folder after idling. But not every time.

#### Provide the steps required to reproduce the problem
1. Listen to a blobtrigger (might be every trigger, I don't know), and call a function in a third party DLL.
2. Watch it fail to load the assembly after going idle, but only sometimes. This means it sometimes recovers the next time it idles.

#### Expected behavior

- Should continue to run and start up after idling.

#### Actual behavior

- Fails to load 3rd party dll's in the bin folder.

#### Related information 
Function is written in C#, simply does this:
```
#r "Lasso.Content.dll"
#r "Lasso.Data.dll"
#r "Lasso.Functions.dll"
#r "Lasso.Domain.dll"

using System;

public static async Task Run(Stream blob, string name, TraceWriter log)
{
    try {
        
        await new Lasso.Functions.EventHandlerFunction().Run(name);
    } catch (Exception e)
    {
        log.Error(e.Message);
    }
}

```

The specific exception:
```
Exception while executing function: Functions.EventHandlerFunction
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.EventHandlerFunction ---> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation. ---> System.TypeLoadException : Could not load type 'Lasso.Functions.EventHandlerFunction' from assembly 'Lasso.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at async Submission#0.Run(Stream blob,String name,TraceWriter log) at  : 17
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Submission#0.Run(Stream blob,String name,TraceWriter log) 
   End of inner exception
   at System.RuntimeMethodHandle.InvokeMethod(Object target,Object[] arguments,Signature sig,Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj,Object[] parameters,Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj,BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context)
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.InvokeAsync[TReflected](Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,Object[] invokeParameters,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,IReadOnlyDictionary`2 parameters,TraceWriter traceWriter,CancellationToken…
```

**Comment by fabiocav** [comment] 2017-03-22 18:03
This is the same issue reported [here](http://stackoverflow.com/questions/42946550/azure-function-fails-to-load-assemblies-after-running-fine-for-a-while), correct?

When did you first notice this issue? Can you share your function app name directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) so we can take a closer look?

**Comment by EmilBechMadsen** [comment] 2017-03-22 18:06
Hi. Yep, that's me aswell.

My function app name is called Lasso-Services, the function called EventHandlerFunction. EU West.

**Comment by fabiocav** [comment] 2017-03-23 00:14
@EmilBechMadsen looking at some logs and execution information, there are a couple of things we can do to resolve this issue:

- Looks like multiple functions are using the same set of assemblies with multiple copies deployed. While this alone is not an issue, it often leads to mismatched deployments if you're dealing with multiple versions. I'd recommend deploying those assemblies to a common folder and referencing them with a relative path (e.g. `#r "..\shared\myassembly.dll"`)
- We noticed some assembly resolution subscriptions pulling from the current domain, which may also cause issues since private assemblies are loaded into a different context and you may end up with an incorrect version or interfering with the runtime logic. Those were also accumulating
- Only the direct assembly reference needs to be added to your function. So you only need to `#r` the assembly that implements your function method and the indirect references will be automatically resolved. While this alone wouldn't cause the issue, it is the recommended practice so you don't have unnecessary metadata references 

I'm still inspecting some of the data, but wanted to share those findings.

**Comment by EmilBechMadsen** [comment] 2017-03-23 08:44
Hi Fabio. Thanks for investigating.

- I'll take a swing at the shared assemblies.
- Are you referring to AppDomain.CurrentDomain.AssemblyResolve in regards to resolutionsubscriptions? If so, that was just an attempt at mitigation, so I suppose we can ignore that.
- Will remove second-degree #r's :)

**Comment by EmilBechMadsen** [comment] 2017-03-23 14:01
I've now implemented above suggestions and will report back in a day or two whether that solved my problem.

If it does indeed work, I think it's because I had another version of the assembly with the same version number, but without the missing EventHandlerFunction class in another function's bin folder. I was not aware that this was a problem, and that they would sometimes run using the assembly of another function.

Something not related to this issue:
The NuGet package management really is dodgy at best. Sometimes a package will install correctly, othertimes it won't. During these changes, some packages would just refuse to install no matter what I did (even if it said it was installed and in the file system), so I ended up resorting to manually putting my otherwise NuGet-referenced dll's in the shared folder as well. This worked fine (Even with WindowsAzure.Storage v. 8.1.1).

**Comment by fabiocav** [comment] 2017-03-23 17:15
Yes, what you've described with the mismatch could indeed cause issues.

About the NuGet, if you have more information you can share (error messages, details about the behavior, etc.) that would help. The restore process uses the same NuGet restore logic (same actual client) as what you'd see locally, the key difference (and what sometimes causes some of the issues with it) is the remote file system, but without more information, we can't really pinpoint that as the cause.

**Comment by EmilBechMadsen** [comment] 2017-03-24 09:48
Preliminary results after 24 hours of running: It worked.

About the NuGet: I didn't really intend on you to fix it, as we all know NuGet is kind of odd sometimes. I can't really say much other than it wouldn't run because it was missing files that I had included in my project.json. When I forced a restore (by changing project.json), it would even say "Installed XXXX" (the exact missing assembly). It still wouldn't run properly. Not even after a restart of the Function app, deleting all NuGet caches or changing the version numbers back and forth.

**Comment by fabiocav** [comment] 2017-03-24 18:27
Good to hear the original issue was resolved.

How often are you running into the NuGet issues? 
It would be good to track it separately, so I'll close this issue for now, and if you run into this again, would you mind opening a new issue and sharing both, the `project.json` AND the `project.lock.json` files (as well as the errors you see)? 

Thanks!

**Closed by fabiocav** 2017-03-24 18:27 UTC
