### ISSUE TITLE
Question: How to actually use outbound blob binding in Azure Functions?

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-webjobs-sdk-script#975] opened 2016-11-23 06:55 UTC
Here's the following blockers I've hit:

* Using `async` so cannot use `out` params
* Cannot return a `Task<Stream>` or `Task<AnyMeaningfulCloudBlobTypes>`, using `$return` binding. - `Cannot bind parameter 'outputBlob' to type CloudBlockBlob. Make sure the parameter Type is supported by the binding. `. All the documentation so far I've seen for this only return a `Task<string>` ?
* Cannot use a `CloudBlockBlob` as an out binding and use methods like `UploadFromStreamAsync(...)` to write to it - `Cannot bind blob to CloudBlockBlob using access Write.`
* _CAN_ use a `Stream` or `CloubBlobStream` and then write to those streams - _however_, I have no way of setting the properties on the blob using these objects (for instance, I want to set the `ContentType`).

There appears to be no way of writing to a blob and setting properties using bindings? Do I have to drop down to directly using the .Net Azure storage api?

**Comment by fabiocav** [comment] 2016-11-23 07:06
This lacks documentation, but in the integration tab, go to advanced and change the 'direction' of your blob binding to 'inout' with that, you'll be able to bind to 'CloudBlockBlob' and do what you need.

**Comment by mathewc** [comment] 2016-11-23 16:12
Related to https://github.com/Azure/azure-webjobs-sdk-script/issues/49. We need to prioritize making this easier to use, I agree. This issue keeps falling onto the back burner.

**Comment by lindydonna** [comment] 2016-11-28 19:20
Duplicate of #49, which is moved to an earlier milestone.

**Closed by lindydonna** 2016-11-28 19:20 UTC

**Comment by nzigel** [comment] 2017-07-10 01:55
How do you set the binding to inout if I am using the attributes in VS2017 preview and don't have a function.json file? 

e.g. public static async Task Run([BlobTrigger("inputcontainer/{name}", Connection = "AzureWebJobsStorage")]CloudBlockBlob myBlob, [Blob("outputcontainer/{name}", Connection = "AzureWebJobsStorage")]CloudBlockBlob outputBlob, string name, TraceWriter log)

**Comment by lindydonna** [comment] 2017-07-10 19:41
@nzigel In the future, please open a new issue so it's not lost.

That example should automatically use inout. If it doesn't, that's a bug .

**Comment by mathewc** [comment] 2018-09-07 16:34
No there isn't an output binding to CloudBlockBlob. You could bind to CloudBlobContainer or CloudBlobDirectory and create blobs using the native SDK APIs.
